USE MULTI
GO


alter table po_movi add
CORTE char(12) not null default '',
GUIA2 CHAR(11) NOT NULL DEFAULT ''

GO

ALTER VIEW VIEW_POS_MOVI
AS
SELECT DISTINCT 
                         dbo.PO_MOVI.ID, MODELADOR.dbo.POS.PO, MODELADOR.dbo.POS.OFI, REPLACE(MODELADOR.dbo.[PO-DETA].COLOR, ' ', '') AS COLOR, 
                         MODELADOR.dbo.[PO-DETA].UBI, dbo.PO_MOVI.EMPRESA AS CIA, MODELADOR.dbo.POS.CLIENTE AS CODCLI, LTRIM(RTRIM(MODELADOR.dbo.CLIENTE.NOMBRE)) 
                         AS NOMCLI, MODELADOR.dbo.[PO-DETA].FOB, LTRIM(RTRIM(MODELADOR.dbo.ESTILOS.ESTCLI)) AS ESTCLI, 
                         LTRIM(RTRIM(MODELADOR.dbo.ESTILOS.DESCRIPCION)) AS ESTILO, dbo.PO_MOVI.MOV, dbo.PO_MOVI.GUIA, dbo.PO_MOVI.RUC, 
                         RSCONCAR.dbo.CP0001MAES.AC_CNOMBRE AS NOMPRO, dbo.PO_MOVI.DEFECTO AS CODDEF, dbo.DEFECTOS.DESCRIPCION AS DESDEF, 
                         dbo.PO_MOVI.PIEZA AS CODPZA, dbo.PIEZAS.DESCRIPCION AS DESPZA, dbo.PO_MOVI.SERVICIO AS CODSER, dbo.SERVICIOS.DESCRIPCION AS DESSER, 
                         dbo.PO_MOVI.CONDICION AS CODCON, dbo.CONDICIONES.DESCRIPCION AS DESCON, MODELADOR.dbo.[PO-DETA].T0, MODELADOR.dbo.[PO-DETA].T1, 
                         MODELADOR.dbo.[PO-DETA].T2, MODELADOR.dbo.[PO-DETA].T3, MODELADOR.dbo.[PO-DETA].T4, MODELADOR.dbo.[PO-DETA].T5, MODELADOR.dbo.[PO-DETA].T6, 
                         MODELADOR.dbo.[PO-DETA].T7, MODELADOR.dbo.[PO-DETA].T8, MODELADOR.dbo.[PO-DETA].T9, MODELADOR.dbo.[PO-DETA].CAN0 AS Q0, 
                         MODELADOR.dbo.[PO-DETA].CAN1 AS Q1, MODELADOR.dbo.[PO-DETA].CAN2 AS Q2, MODELADOR.dbo.[PO-DETA].CAN3 AS Q3, 
                         MODELADOR.dbo.[PO-DETA].CAN4 AS Q4, MODELADOR.dbo.[PO-DETA].CAN5 AS Q5, MODELADOR.dbo.[PO-DETA].CAN6 AS Q6, 
                         MODELADOR.dbo.[PO-DETA].CAN7 AS Q7, MODELADOR.dbo.[PO-DETA].CAN8 AS Q8, MODELADOR.dbo.[PO-DETA].CAN9 AS Q9, dbo.PO_MOVI.CAN0 AS C0, 
                         dbo.PO_MOVI.CAN1 AS C1, dbo.PO_MOVI.CAN2 AS C2, dbo.PO_MOVI.CAN3 AS C3, dbo.PO_MOVI.CAN4 AS C4, dbo.PO_MOVI.CAN5 AS C5, dbo.PO_MOVI.CAN6 AS C6, 
                         dbo.PO_MOVI.CAN7 AS C7, dbo.PO_MOVI.CAN8 AS C8, dbo.PO_MOVI.CAN9 AS C9, dbo.PO_MOVI.MOTIVO AS CODMOT, dbo.MOTIVOS.DESCRIPCION AS DESMOT, 
                         dbo.PO_MOVI.BOLSA, dbo.PO_MOVI.LINEA AS CODLIN, dbo.LINEAS.DESCRIPCION AS DESLIN, MODELADOR.dbo.ESTILOS.CODARTICULO AS CODART, 
                         MODELADOR.dbo.ESTILOS.DESMODELADOR AS DESART, MODELADOR.dbo.COTIZACION.PROTO, MODELADOR.dbo.COTIZACION.VERSION, dbo.PO_MOVI.ESTADO, 
                         MODELADOR.dbo.POS.CODEST, dbo.PO_MOVI.FECDOC, dbo.PO_MOVI.FECEMB, dbo.PO_MOVI.FACEXP, dbo.PO_MOVI.FACPRO, dbo.PO_MOVI.FECPRO, 
                         dbo.PO_MOVI.NUMSER, AL0001ARTI.AR_CDESCRI, dbo.PO_MOVI.GUIA2, dbo.PO_MOVI.CORTE
FROM            MODELADOR.dbo.COTIZACION INNER JOIN
                         dbo.PO_MOVI INNER JOIN
                         RSCONCAR.dbo.CP0001MAES ON RSCONCAR.dbo.CP0001MAES.AC_CCODIGO = dbo.PO_MOVI.RUC COLLATE Modern_Spanish_CI_AS INNER JOIN
                         dbo.CONDICIONES ON dbo.CONDICIONES.CODIGO = dbo.PO_MOVI.CONDICION INNER JOIN
                         dbo.DEFECTOS ON dbo.DEFECTOS.CODIGO = dbo.PO_MOVI.DEFECTO INNER JOIN
                         dbo.PIEZAS ON dbo.PO_MOVI.PIEZA = dbo.PIEZAS.CODIGO INNER JOIN
                         dbo.SERVICIOS ON dbo.PO_MOVI.SERVICIO = dbo.SERVICIOS.CODIGO INNER JOIN
                         MODELADOR.dbo.[PO-DETA] INNER JOIN
                         MODELADOR.dbo.POS ON MODELADOR.dbo.[PO-DETA].PO = MODELADOR.dbo.POS.PO INNER JOIN
                         MODELADOR.dbo.CLIENTE ON MODELADOR.dbo.POS.CLIENTE = MODELADOR.dbo.CLIENTE.CODIGO INNER JOIN
                         MODELADOR.dbo.ESTILOS ON MODELADOR.dbo.POS.CLIENTE = MODELADOR.dbo.ESTILOS.CLIENTE AND 
                         MODELADOR.dbo.POS.CODEST = MODELADOR.dbo.ESTILOS.CODEST ON dbo.PO_MOVI.UBI = MODELADOR.dbo.[PO-DETA].UBI AND 
                         dbo.PO_MOVI.PO = MODELADOR.dbo.[PO-DETA].PO INNER JOIN
                         dbo.MOTIVOS ON dbo.PO_MOVI.MOTIVO = dbo.MOTIVOS.CODIGO INNER JOIN
                         dbo.LINEAS ON dbo.PO_MOVI.LINEA = dbo.LINEAS.CODIGO ON MODELADOR.dbo.COTIZACION.COTIZACION = MODELADOR.dbo.POS.COTIZACION FULL OUTER JOIN
                         RSFACCAR.dbo.AL0001ARTI AS AL0001ARTI ON AL0001ARTI.AR_CCODIGO = SUBSTRING(MODELADOR.dbo.ESTILOS.CODARTICULO, 8, 13) 
                         + '00000' COLLATE Modern_Spanish_CI_AS
WHERE        (NOT (dbo.PO_MOVI.ID IS NULL))
GO



ALTER procedure  [dbo].[FICHAPOSmovi]  
@IDD VARCHAR(10) as

if @IDD = 'AUTO' or @IDD =''

select   'AUTO' AS [ID],
	'' as PO,		'' as OFI,		'' AS COLOR,	'' AS UBI,		'' AS CIA,		'' as CODCLI, 	'' as NOMCLI,	
	0  as FOB,		'' as ESTCLI,	'' as ESTILO,	'' as MOV,		'' AS GUIA,		'' AS RUC,		'' AS NOMPRO,
	'' as CODDEF,	'' as DESDEF,	'' as CODPZA,	'' as DESPZA,	'' AS CODSER,	'' AS DESSER,
	'' AS CODCON,	'' as DESCON,	'' as T0,		0  as C0	,	'' AS T1,		0  as C1,
	'' AS T2,		0  AS C2,		'' AS T3,		0  AS C3,		'' AS T4,		0  as C4,
	'' AS T5,		0  AS C5,		'' AS T6,		0  AS C6,		'' AS T7,		0  as C7,
	'' AS T8,		0  AS C8,		'' AS T9,		0  AS C9,		'' as estado,	'' AS CODEST,
	0  as Q0,		0  AS Q1,		0  AS Q2,		0  AS Q3,		0  AS Q4,		0  AS Q5,		
	0  AS Q6,		0  AS Q7,		0  AS Q8,		0  AS Q9,		getdate() as fecdoc	,
	'' as codmot,	'' as DESMOT,	'' AS BOLSA,	'' AS CODLIN,	'' AS DESLIN,	'' AS GUIA2, '' AS CORTE
else
SELECT	ID, PO, OFI, COLOR, UBI, CIA, CODCLI, NOMCLI, 
		FOB, ESTCLI, ESTILO, MOV, GUIA, RUC, NOMPRO, 
		CODDEF, DESDEF, CODPZA, DESPZA, CODSER, 
		DESSER, CODCON, DESCON, T0, C0, T1, C1, 
		T2, C2, T3, C3, T4, C4, T5, C5, T6, C6, 
		T7, C7, T8, C8, T9, C9, ESTADO, codest,
		q0, q1, q2,q3, q4, q5, q6, q7, q8, q9, FECDOC,
		CODMOT, DESMOT, BOLSA, CODLIN, DESLIN, GUIA2, CORTE
FROM MULTI.dbo.VIEW_POS_MOVI
WHERE ID = @IDD
GO