

/*******************************************************************
	HAY QUE IR CAMBIANDO LAS EMPRESAS PARA LA APERTURA OFICIAL
	ACA Y EN EL SP RS_MOV_I_ENT_SAL
	CASO CONTRARIO NO FUNCIONARÁ.....

	ejecutar primero lo que está comentado, que es el SP
	AL QUE LLAMA EL CURSOR DE LA SEGUNDA PARTE
********************************************************************/
/*

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
alter PROCEDURE [dbo].[RS_MOV_I_ENT_SAL]
(
	@CALMA	char(4),
	@CTD	char(2),
	@CNUMDOC	char(11)	
)
AS
set nocount on

Select Top 1 * Into #CAB
From RSFACCAR..AL0001MOVC
Where c5_calma=@calma and c5_ctd=@ctd and c5_cnumdoc=@CNUMDOC AND C5_CCODAUT='' AND C5_CSITUA<>'A'

Select C6_CALMA,C6_CTD,C6_CNUMDOC,C6_CITEM,C5_DFECDOC,C5_CRFTDOC,C5_CRFNDOC,C5_CTIPMOV,C5_CCODMOV,C6_CCODIGO,C6_CDESCRI,
	C6_NCANTID,C6_NCANTID AS NCANTIDPROV,C5_CCODPRO,C5_CNOMPRO,C5_CNUMORD
Into #DETALLE
From RSFACCAR..AL0001MOVD INNER JOIN #CAB ON (C6_CALMA=C5_CALMA AND C6_CTD=C5_CTD AND C6_CNUMDOC=C5_CNUMDOC)

DELETE #DETALLE
WHERE C6_CCODIGO IN('TXT','.')

Insert into RS_ALMOVD0001(CALMA,CTD,CNUMDOC,CITEM,DFECDOC,CRFTDOC,CRFNDOC,CTIPMOV,CCODMOV,CCODIGO,CDESCRI,NCANTID,NCANTIDPROV,CCODPROV,CNOMPROV,CNUMORD,ESTADO)
Select *, 'V' AS ESTADO 
From #DETALLE

UPDATE RSFACCAR..AL0001MOVC
SET C5_CCODAUT='S'
FROM RSFACCAR..AL0001MOVC A INNER JOIN #CAB B on(A.C5_CALMA=B.C5_CALMA AND A.C5_CTD=B.C5_CTD AND A.C5_CNUMDOC=B.C5_CNUMDOC)
*/





SELECT * INTO #Cabecera from RSFACCAR..AL0001MOVC
WHERE YEAR(C5_DFECCRE)>2010 AND C5_CCODAUT='' AND C5_CSITUA<>'A'

DECLARE	@CALMA		char(4)
DECLARE	@CTD		char(2)
DECLARE	@CNUMDOC	char(11)	
--

DECLARE CRS_MOV CURSOR FAST_FORWARD FOR
SELECT c5_calma,c5_ctd,c5_cnumdoc
from #Cabecera 
OPEN CRS_MOV
	
	FETCH NEXT FROM CRS_MOV INTO @CALMA, @CTD, @CNUMDOC
	WHILE @@FETCH_STATUS = 0 BEGIN

		IF NOT EXISTS(SELECT * FROM RS_ALMOVD0001 WHERE CALMA=@CALMA AND CTD=@CTD AND CNUMDOC=@CNUMDOC)	
			EXEC RS_MOV_I_ENT_SAL @CALMA, @CTD, @CNUMDOC
	
	FETCH NEXT FROM CRS_MOV INTO @CALMA, @CTD, @CNUMDOC
END
CLOSE CRS_MOV DEALLOCATE CRS_MOV
DROP TABLE #CABECERA

