USE [multi]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TABLA DE EMPRESAS
CREATE VIEW VIEW_CIAS AS 
SELECT CT_CIA AS CIA, CT_NOMBRE AS NOMBRE FROM RSconCAR..cpciae
GO

CREATE TABLE [dbo].[USUARIOS](
	[USUARIO] [char](4) NOT NULL PRIMARY KEY,
	[CLAVE] [char](10) NULL,
	[NOMBRES] [char](50) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USR-CIA](
	[USUARIO]	[char](4) NOT NULL ,
	[CIA]		[char](4) not null 	
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[USR-OPC](
	[USUARIO] [char](15) NOT NULL,
	[MENU] [char](2) NOT NULL,
	[SUBMENU] [char](2) NOT NULL,
	[PERFIL] [char](3) NULL,
 CONSTRAINT [PK_USR-OPC] PRIMARY KEY CLUSTERED 
(	[USUARIO] ASC,
	[MENU] ASC,
	[SUBMENU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
--DROP TABLE SUBMENU
CREATE TABLE [dbo].[SUBMENU](
	[MENU] [char](2) NOT NULL,
	[SUBMENU] [char](2) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[PROGRAMA] [varchar](100) NULL,
	[ESTADO] [char](1) NULL,
 CONSTRAINT [PK_SUBMENU] PRIMARY KEY CLUSTERED 
(
	[MENU] ASC,
	[SUBMENU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
--DROP TABLE MENU
CREATE TABLE [dbo].[MENU](
	[MENU] [char](2) NOT NULL,
	[DESMENU] [varchar](50) NULL,
 CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED 
(
	[MENU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE VIEW VIEW_USR_CIA AS 
SELECT dbo.[USR-CIA].USUARIO, dbo.[USR-CIA].CIA, dbo.VIEW_CIAS.NOMBRE
FROM  dbo.[USR-CIA] INNER JOIN
               dbo.VIEW_CIAS ON dbo.[USR-CIA].CIA = dbo.VIEW_CIAS.CIA COLLATE SQL_Latin1_General_CP1_CI_AI

--DROP VIEW VIEW_MENU_USR
CREATE VIEW VIEW_MENU_USR as
SELECT distinct TOP (100) PERCENT  dbo.MENU.MENU, dbo.SUBMENU.SUBMENU, dbo.MENU.DESMENU, dbo.SUBMENU.DESCRIPCION, dbo.SUBMENU.PROGRAMA, 
               dbo.SUBMENU.ESTADO, dbo.[USR-OPC].USUARIO
FROM  dbo.MENU INNER JOIN
               dbo.[USR-OPC] ON dbo.MENU.MENU = dbo.[USR-OPC].MENU INNER JOIN
               dbo.SUBMENU ON dbo.MENU.MENU = dbo.SUBMENU.MENU
ORDER BY dbo.MENU.MENU, dbo.SUBMENU.SUBMENU


INSERT INTO USUARIOS (USUARIO, CLAVE, NOMBRES)
VALUES ('SIST', 'FENIX', 'SISTEMAS')

INSERT INTO [USR-CIA] (USUARIO, CIA) VALUES ('SIST','0001')
INSERT INTO [USR-CIA] (USUARIO, CIA) VALUES ('SIST','0002')
INSERT INTO [USR-CIA] (USUARIO, CIA) VALUES ('SIST','0006')
INSERT INTO [USR-CIA] (USUARIO, CIA) VALUES ('SIST','0008')

INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '01', '01', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '01', '02', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '02', '01', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '01', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '02', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '03', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '04', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '05', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '06', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '07', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '08', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '03', '09', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '01', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '02', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '03', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '04', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '05', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '06', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '07', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '08', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '09', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '04', '10', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '05', '01', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '05', '02', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '05', '03', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '05', '04', '1')
INSERT INTO [USR-OPC] (USUARIO, MENU,SUBMENU, PERFIL) VALUES ('SIST', '05', '05', '1')

INSERT INTO MENU (MENU, DESMENU) VALUES('01', 'MAESTROS')
INSERT INTO MENU (MENU, DESMENU) VALUES('02', 'PRODUCCION')
INSERT INTO MENU (MENU, DESMENU) VALUES('03', 'LOGISTICA')
INSERT INTO MENU (MENU, DESMENU) VALUES('04', 'ALMACEN')
INSERT INTO MENU (MENU, DESMENU) VALUES('05', 'SISTEMAS')

INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('01','01','Tipos Mov-Almacen', 'TIPMOV.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('01','02','Clientes', 'CLIENTES.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('02','01','Consulta Telas', 'TELAS.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','01','Consulta OC - Contra', 'CONTRAOC.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','02','Consulta', 'CONSULOC.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','03','Cambio Edo OC', 'ESTADOOC.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','04','Orden Servicio', 'OSERVICIO.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','05','Edita Doc ALm', 'EDITADOCALM.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','06','Prn Stock Minimo', 'MINIMOS.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','07','Elimina Partes E/S', 'ELIMINAPARTE.ASP','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','08','-.-', 'BLANCO.HTM','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('03','09','*.*', 'BLANCO.HTM','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','01','Conteo Salida Guia', 'CONTEOSALE.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','02','Conteo Devolución', 'CONTEOENTRA.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','03','Stock Almacen', 'STKALMACEN.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','04','PRN Movimientos', 'MOVIMIENTOS.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','05','Edicion Ing/Sal', 'EDICIONES.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','06','PRN E/S Almacen', 'QRYMOVIMIENTOS.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','07','Transferir RS', 'TRANSFERENCIAS.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','08','OC Sobreatendidas', 'SOBREATENDIDO.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','09','Movim Fecha', 'QRYMOVIM.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('04','10','Valida Mov-Alm', 'VALIDA.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('05','01','Menus', 'MENUS.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('05','02','Sub-Menus', 'SUBMENUS.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('05','03','Usuarios', 'USUARIOS.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('05','04','Usr-Cia', 'USRCIA.asp','A')
INSERT INTO SUBMENU (MENU, SUBMENU, DESCRIPCION, PROGRAMA, ESTADO) 
VALUES ('05','05','Usr-Opc', 'USROPC.asp','A')
