USE [multi]
GO


CREATE TABLE [dbo].[DEFECTOS](
	[CODIGO] [char](2) NOT NULL PRIMARY KEY,
	[DESCRIPCION] VARCHAR(50) ,
	[USUARIO] CHAR(4),
	[FECHA] [SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO] CHAR(1) DEFAULT 'A'
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CONDICIONES](
	[CODIGO] [char](2) NOT NULL PRIMARY KEY,
	[DESCRIPCION] VARCHAR(50) ,
	[USUARIO] CHAR(4),
	[FECHA] [SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO] CHAR(1) DEFAULT 'A'
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PIEZAS](
	[CODIGO] [char](2) NOT NULL PRIMARY KEY,
	[DESCRIPCION] VARCHAR(50) ,
	[USUARIO] CHAR(4),
	[FECHA] [SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO] CHAR(1) DEFAULT 'A'
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SERVICIOS](
	[CODIGO] [char](2) NOT NULL PRIMARY KEY,
	[DESCRIPCION] VARCHAR(50) ,
	[USUARIO] CHAR(4),
	[FECHA] [SMALLdatetime] DEFAULT GETDATE(),
	[ESTADO] CHAR(1) DEFAULT 'A'
) ON [PRIMARY]
GO
