USE [MULTI]
GO
/****** Object:  Table [dbo].[RS_ALMOVC]    Script Date: 07/26/2013 14:37:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
/*DROP TABLE RS_ALMOVC0001
DROP TABLE RS_ALMOVC0002
DROP TABLE RS_ALMOVC0006
DROP TABLE RS_ALMOVC0008
*/
CREATE TABLE [dbo].[RS_ALMOVC0001](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[CP_CTIPDOC] [char](2) NOT NULL,
	[CP_CNUMDOC] [char](20) NOT NULL,
	[FECCREA] [datetime] NOT NULL,
	[FECMOD] [datetime] NULL,
	[CODUSUCRE] [varchar](15) NOT NULL,
	[CODUSUMOD] [varchar](15) NULL,
 CONSTRAINT [PK_RS_ALMOVC0001] PRIMARY KEY CLUSTERED 
(
	[C5_CALMA] ASC,
	[C5_CTD] ASC,
	[C5_CNUMDOC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[RS_ALMOVC0002](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[CP_CTIPDOC] [char](2) NOT NULL,
	[CP_CNUMDOC] [char](20) NOT NULL,
	[FECCREA] [datetime] NOT NULL,
	[FECMOD] [datetime] NULL,
	[CODUSUCRE] [varchar](15) NOT NULL,
	[CODUSUMOD] [varchar](15) NULL,
 CONSTRAINT [PK_RS_ALMOVC0002] PRIMARY KEY CLUSTERED 
(
	[C5_CALMA] ASC,
	[C5_CTD] ASC,
	[C5_CNUMDOC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[RS_ALMOVC0006](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[CP_CTIPDOC] [char](2) NOT NULL,
	[CP_CNUMDOC] [char](20) NOT NULL,
	[FECCREA] [datetime] NOT NULL,
	[FECMOD] [datetime] NULL,
	[CODUSUCRE] [varchar](15) NOT NULL,
	[CODUSUMOD] [varchar](15) NULL,
 CONSTRAINT [PK_RS_ALMOVC0006] PRIMARY KEY CLUSTERED 
(
	[C5_CALMA] ASC,
	[C5_CTD] ASC,
	[C5_CNUMDOC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[RS_ALMOVC0008](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[CP_CTIPDOC] [char](2) NOT NULL,
	[CP_CNUMDOC] [char](20) NOT NULL,
	[FECCREA] [datetime] NOT NULL,
	[FECMOD] [datetime] NULL,
	[CODUSUCRE] [varchar](15) NOT NULL,
	[CODUSUMOD] [varchar](15) NULL,
 CONSTRAINT [PK_RS_ALMOVC0008] PRIMARY KEY CLUSTERED 
(
	[C5_CALMA] ASC,
	[C5_CTD] ASC,
	[C5_CNUMDOC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[RS_ALMOVC_Del0001](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[C5_CLOCALI] [char](4) NOT NULL,
	[C5_DFECDOC] [datetime] NULL,
	[C5_DFECVEN] [datetime] NULL,
	[C5_CTIPMOV] [char](1) NOT NULL,
	[C5_CCODMOV] [char](2) NOT NULL,
	[C5_CSITUA] [char](1) NOT NULL,
	[C5_CRFTDOC] [char](2) NOT NULL,
	[C5_CRFNDOC] [char](24) NOT NULL,
	[C5_CSOLI] [char](3) NOT NULL,
	[C5_CCENCOS] [char](6) NOT NULL,
	[C5_CRFALMA] [char](4) NOT NULL,
	[C5_CGLOSA1] [char](30) NOT NULL,
	[C5_CGLOSA2] [char](30) NOT NULL,
	[C5_CGLOSA3] [char](30) NOT NULL,
	[C5_CTIPANE] [char](1) NOT NULL,
	[C5_CCODANE] [varchar](18) NOT NULL,
	[C5_DFECCRE] [datetime] NULL,
	[C5_CUSUCRE] [char](5) NOT NULL,
	[C5_DFECMOD] [datetime] NULL,
	[C5_CUSUMOD] [char](5) NOT NULL,
	[C5_CCODCLI] [char](18) NOT NULL,
	[C5_CNOMCLI] [char](50) NOT NULL,
	[C5_CRUC] [char](18) NOT NULL,
	[C5_CCODCAD] [char](4) NOT NULL,
	[C5_CCODINT] [char](10) NOT NULL,
	[C5_CCODTRA] [char](18) NOT NULL,
	[C5_CNOMTRA] [varchar](50) NOT NULL,
	[C5_CCODVEH] [char](18) NOT NULL,
	[C5_CTIPGUI] [char](2) NOT NULL,
	[C5_CSITGUI] [char](1) NOT NULL,
	[C5_CGUIFAC] [char](1) NOT NULL,
	[C5_CDESTIN] [char](4) NOT NULL,
	[C5_CDIRENV] [varchar](80) NOT NULL,
	[C5_CNUMORD] [char](20) NOT NULL,
	[C5_CTIPORD] [char](1) NOT NULL,
	[C5_CGUIDEV] [char](1) NOT NULL,
	[C5_CCODPRO] [char](18) NOT NULL,
	[C5_CNOMPRO] [varchar](50) NOT NULL,
	[C5_CCIAS] [char](4) NOT NULL,
	[C5_CFORVEN] [char](3) NOT NULL,
	[C5_CCODMON] [char](2) NOT NULL,
	[C5_CVENDE] [char](5) NOT NULL,
	[C5_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C5_CCODAGE] [char](4) NOT NULL,
	[C5_CNUMPED] [char](11) NOT NULL,
	[C5_CDIRECC] [varchar](80) NOT NULL,
	[C5_NIMPORT] [numeric](13, 2) NOT NULL,
	[C5_CTIPO] [char](1) NOT NULL,
	[C5_CSUBDIA] [char](4) NOT NULL,
	[C5_CCOMPRO] [char](6) NOT NULL,
	[C5_NPORDE1] [numeric](5, 2) NOT NULL,
	[C5_NPORDE2] [numeric](5, 2) NOT NULL,
	[C5_CTF] [char](2) NOT NULL,
	[C5_NFLETE] [numeric](9, 2) NOT NULL,
	[C5_CCODAUT] [varchar](15) NOT NULL,
	[C5_CRFTDO2] [char](2) NOT NULL,
	[C5_CRFNDO2] [char](24) NOT NULL,
	[C5_CNUMLIQ] [char](23) NOT NULL,
	[C5_CORDEN] [char](18) NOT NULL,
	[C5_CTIPOGS] [char](1) NOT NULL,
	[C5_DFECANU] [datetime] NULL,
	[C5_CCODFER] [char](18) NOT NULL,
	[C5_DFECEMB] [datetime] NULL,
	[C5_CGLOSA4] [char](50) NOT NULL,
	[C5_CVENDE2] [char](5) NOT NULL,
	[C5_CESTDEV] [char](1) NOT NULL,
	[C5_CEXTOR] [char](1) NOT NULL,
	[C5_CRENOM] [varchar](80) NOT NULL,
	[C5_CRERUC] [char](18) NOT NULL,
	[C5_CREREF] [varchar](80) NOT NULL,
	[C5_CDSNOM] [varchar](80) NOT NULL,
	[C5_CDSRUC] [char](18) NOT NULL,
	[C5_CLLECIU] [char](12) NOT NULL,
	[C5_CPARCIU] [char](12) NOT NULL,
	[C5_CTTRACT] [char](10) NOT NULL,
	[C5_CTRASRE] [char](10) NOT NULL,
	[C5_CTRAREM] [char](10) NOT NULL,
	[C5_CLICCON] [varchar](25) NOT NULL,
	[C5_CSBNOM] [varchar](80) NOT NULL,
	[C5_CSBRUC] [char](18) NOT NULL,
	[C5_CSBMTC] [varchar](25) NOT NULL,
	[C5_CMONPER] [char](2) NOT NULL,
	[C5_NIMPPER] [numeric](13, 2) NOT NULL,
	[C5_CFPERCP] [char](1) NOT NULL,
	[C5_CESTFIN] [char](1) NOT NULL,
	[C5_CFLGPEN] [char](1) NOT NULL,
	[C5_CTIPFOR] [char](2) NOT NULL,
	[C5_NPORPER] [numeric](8, 2) NOT NULL,
	[C5_CFLGTRM] [char](1) NOT NULL,
	[C5_USUDEL] [varchar](15) NULL,
	[C5_FECDEL] [datetime] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RS_ALMOVC_Del0002](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[C5_CLOCALI] [char](4) NOT NULL,
	[C5_DFECDOC] [datetime] NULL,
	[C5_DFECVEN] [datetime] NULL,
	[C5_CTIPMOV] [char](1) NOT NULL,
	[C5_CCODMOV] [char](2) NOT NULL,
	[C5_CSITUA] [char](1) NOT NULL,
	[C5_CRFTDOC] [char](2) NOT NULL,
	[C5_CRFNDOC] [char](24) NOT NULL,
	[C5_CSOLI] [char](3) NOT NULL,
	[C5_CCENCOS] [char](6) NOT NULL,
	[C5_CRFALMA] [char](4) NOT NULL,
	[C5_CGLOSA1] [char](30) NOT NULL,
	[C5_CGLOSA2] [char](30) NOT NULL,
	[C5_CGLOSA3] [char](30) NOT NULL,
	[C5_CTIPANE] [char](1) NOT NULL,
	[C5_CCODANE] [varchar](18) NOT NULL,
	[C5_DFECCRE] [datetime] NULL,
	[C5_CUSUCRE] [char](5) NOT NULL,
	[C5_DFECMOD] [datetime] NULL,
	[C5_CUSUMOD] [char](5) NOT NULL,
	[C5_CCODCLI] [char](18) NOT NULL,
	[C5_CNOMCLI] [char](50) NOT NULL,
	[C5_CRUC] [char](18) NOT NULL,
	[C5_CCODCAD] [char](4) NOT NULL,
	[C5_CCODINT] [char](10) NOT NULL,
	[C5_CCODTRA] [char](18) NOT NULL,
	[C5_CNOMTRA] [varchar](50) NOT NULL,
	[C5_CCODVEH] [char](18) NOT NULL,
	[C5_CTIPGUI] [char](2) NOT NULL,
	[C5_CSITGUI] [char](1) NOT NULL,
	[C5_CGUIFAC] [char](1) NOT NULL,
	[C5_CDESTIN] [char](4) NOT NULL,
	[C5_CDIRENV] [varchar](80) NOT NULL,
	[C5_CNUMORD] [char](20) NOT NULL,
	[C5_CTIPORD] [char](1) NOT NULL,
	[C5_CGUIDEV] [char](1) NOT NULL,
	[C5_CCODPRO] [char](18) NOT NULL,
	[C5_CNOMPRO] [varchar](50) NOT NULL,
	[C5_CCIAS] [char](4) NOT NULL,
	[C5_CFORVEN] [char](3) NOT NULL,
	[C5_CCODMON] [char](2) NOT NULL,
	[C5_CVENDE] [char](5) NOT NULL,
	[C5_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C5_CCODAGE] [char](4) NOT NULL,
	[C5_CNUMPED] [char](11) NOT NULL,
	[C5_CDIRECC] [varchar](80) NOT NULL,
	[C5_NIMPORT] [numeric](13, 2) NOT NULL,
	[C5_CTIPO] [char](1) NOT NULL,
	[C5_CSUBDIA] [char](4) NOT NULL,
	[C5_CCOMPRO] [char](6) NOT NULL,
	[C5_NPORDE1] [numeric](5, 2) NOT NULL,
	[C5_NPORDE2] [numeric](5, 2) NOT NULL,
	[C5_CTF] [char](2) NOT NULL,
	[C5_NFLETE] [numeric](9, 2) NOT NULL,
	[C5_CCODAUT] [varchar](15) NOT NULL,
	[C5_CRFTDO2] [char](2) NOT NULL,
	[C5_CRFNDO2] [char](24) NOT NULL,
	[C5_CNUMLIQ] [char](23) NOT NULL,
	[C5_CORDEN] [char](18) NOT NULL,
	[C5_CTIPOGS] [char](1) NOT NULL,
	[C5_DFECANU] [datetime] NULL,
	[C5_CCODFER] [char](18) NOT NULL,
	[C5_DFECEMB] [datetime] NULL,
	[C5_CGLOSA4] [char](50) NOT NULL,
	[C5_CVENDE2] [char](5) NOT NULL,
	[C5_CESTDEV] [char](1) NOT NULL,
	[C5_CEXTOR] [char](1) NOT NULL,
	[C5_CRENOM] [varchar](80) NOT NULL,
	[C5_CRERUC] [char](18) NOT NULL,
	[C5_CREREF] [varchar](80) NOT NULL,
	[C5_CDSNOM] [varchar](80) NOT NULL,
	[C5_CDSRUC] [char](18) NOT NULL,
	[C5_CLLECIU] [char](12) NOT NULL,
	[C5_CPARCIU] [char](12) NOT NULL,
	[C5_CTTRACT] [char](10) NOT NULL,
	[C5_CTRASRE] [char](10) NOT NULL,
	[C5_CTRAREM] [char](10) NOT NULL,
	[C5_CLICCON] [varchar](25) NOT NULL,
	[C5_CSBNOM] [varchar](80) NOT NULL,
	[C5_CSBRUC] [char](18) NOT NULL,
	[C5_CSBMTC] [varchar](25) NOT NULL,
	[C5_CMONPER] [char](2) NOT NULL,
	[C5_NIMPPER] [numeric](13, 2) NOT NULL,
	[C5_CFPERCP] [char](1) NOT NULL,
	[C5_CESTFIN] [char](1) NOT NULL,
	[C5_CFLGPEN] [char](1) NOT NULL,
	[C5_CTIPFOR] [char](2) NOT NULL,
	[C5_NPORPER] [numeric](8, 2) NOT NULL,
	[C5_CFLGTRM] [char](1) NOT NULL,
	[C5_USUDEL] [varchar](15) NULL,
	[C5_FECDEL] [datetime] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RS_ALMOVC_Del0006](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[C5_CLOCALI] [char](4) NOT NULL,
	[C5_DFECDOC] [datetime] NULL,
	[C5_DFECVEN] [datetime] NULL,
	[C5_CTIPMOV] [char](1) NOT NULL,
	[C5_CCODMOV] [char](2) NOT NULL,
	[C5_CSITUA] [char](1) NOT NULL,
	[C5_CRFTDOC] [char](2) NOT NULL,
	[C5_CRFNDOC] [char](24) NOT NULL,
	[C5_CSOLI] [char](3) NOT NULL,
	[C5_CCENCOS] [char](6) NOT NULL,
	[C5_CRFALMA] [char](4) NOT NULL,
	[C5_CGLOSA1] [char](30) NOT NULL,
	[C5_CGLOSA2] [char](30) NOT NULL,
	[C5_CGLOSA3] [char](30) NOT NULL,
	[C5_CTIPANE] [char](1) NOT NULL,
	[C5_CCODANE] [varchar](18) NOT NULL,
	[C5_DFECCRE] [datetime] NULL,
	[C5_CUSUCRE] [char](5) NOT NULL,
	[C5_DFECMOD] [datetime] NULL,
	[C5_CUSUMOD] [char](5) NOT NULL,
	[C5_CCODCLI] [char](18) NOT NULL,
	[C5_CNOMCLI] [char](50) NOT NULL,
	[C5_CRUC] [char](18) NOT NULL,
	[C5_CCODCAD] [char](4) NOT NULL,
	[C5_CCODINT] [char](10) NOT NULL,
	[C5_CCODTRA] [char](18) NOT NULL,
	[C5_CNOMTRA] [varchar](50) NOT NULL,
	[C5_CCODVEH] [char](18) NOT NULL,
	[C5_CTIPGUI] [char](2) NOT NULL,
	[C5_CSITGUI] [char](1) NOT NULL,
	[C5_CGUIFAC] [char](1) NOT NULL,
	[C5_CDESTIN] [char](4) NOT NULL,
	[C5_CDIRENV] [varchar](80) NOT NULL,
	[C5_CNUMORD] [char](20) NOT NULL,
	[C5_CTIPORD] [char](1) NOT NULL,
	[C5_CGUIDEV] [char](1) NOT NULL,
	[C5_CCODPRO] [char](18) NOT NULL,
	[C5_CNOMPRO] [varchar](50) NOT NULL,
	[C5_CCIAS] [char](4) NOT NULL,
	[C5_CFORVEN] [char](3) NOT NULL,
	[C5_CCODMON] [char](2) NOT NULL,
	[C5_CVENDE] [char](5) NOT NULL,
	[C5_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C5_CCODAGE] [char](4) NOT NULL,
	[C5_CNUMPED] [char](11) NOT NULL,
	[C5_CDIRECC] [varchar](80) NOT NULL,
	[C5_NIMPORT] [numeric](13, 2) NOT NULL,
	[C5_CTIPO] [char](1) NOT NULL,
	[C5_CSUBDIA] [char](4) NOT NULL,
	[C5_CCOMPRO] [char](6) NOT NULL,
	[C5_NPORDE1] [numeric](5, 2) NOT NULL,
	[C5_NPORDE2] [numeric](5, 2) NOT NULL,
	[C5_CTF] [char](2) NOT NULL,
	[C5_NFLETE] [numeric](9, 2) NOT NULL,
	[C5_CCODAUT] [varchar](15) NOT NULL,
	[C5_CRFTDO2] [char](2) NOT NULL,
	[C5_CRFNDO2] [char](24) NOT NULL,
	[C5_CNUMLIQ] [char](23) NOT NULL,
	[C5_CORDEN] [char](18) NOT NULL,
	[C5_CTIPOGS] [char](1) NOT NULL,
	[C5_DFECANU] [datetime] NULL,
	[C5_CCODFER] [char](18) NOT NULL,
	[C5_DFECEMB] [datetime] NULL,
	[C5_CGLOSA4] [char](50) NOT NULL,
	[C5_CVENDE2] [char](5) NOT NULL,
	[C5_CESTDEV] [char](1) NOT NULL,
	[C5_CEXTOR] [char](1) NOT NULL,
	[C5_CRENOM] [varchar](80) NOT NULL,
	[C5_CRERUC] [char](18) NOT NULL,
	[C5_CREREF] [varchar](80) NOT NULL,
	[C5_CDSNOM] [varchar](80) NOT NULL,
	[C5_CDSRUC] [char](18) NOT NULL,
	[C5_CLLECIU] [char](12) NOT NULL,
	[C5_CPARCIU] [char](12) NOT NULL,
	[C5_CTTRACT] [char](10) NOT NULL,
	[C5_CTRASRE] [char](10) NOT NULL,
	[C5_CTRAREM] [char](10) NOT NULL,
	[C5_CLICCON] [varchar](25) NOT NULL,
	[C5_CSBNOM] [varchar](80) NOT NULL,
	[C5_CSBRUC] [char](18) NOT NULL,
	[C5_CSBMTC] [varchar](25) NOT NULL,
	[C5_CMONPER] [char](2) NOT NULL,
	[C5_NIMPPER] [numeric](13, 2) NOT NULL,
	[C5_CFPERCP] [char](1) NOT NULL,
	[C5_CESTFIN] [char](1) NOT NULL,
	[C5_CFLGPEN] [char](1) NOT NULL,
	[C5_CTIPFOR] [char](2) NOT NULL,
	[C5_NPORPER] [numeric](8, 2) NOT NULL,
	[C5_CFLGTRM] [char](1) NOT NULL,
	[C5_USUDEL] [varchar](15) NULL,
	[C5_FECDEL] [datetime] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RS_ALMOVC_Del0008](
	[C5_CALMA] [char](4) NOT NULL,
	[C5_CTD] [char](2) NOT NULL,
	[C5_CNUMDOC] [char](11) NOT NULL,
	[C5_CLOCALI] [char](4) NOT NULL,
	[C5_DFECDOC] [datetime] NULL,
	[C5_DFECVEN] [datetime] NULL,
	[C5_CTIPMOV] [char](1) NOT NULL,
	[C5_CCODMOV] [char](2) NOT NULL,
	[C5_CSITUA] [char](1) NOT NULL,
	[C5_CRFTDOC] [char](2) NOT NULL,
	[C5_CRFNDOC] [char](24) NOT NULL,
	[C5_CSOLI] [char](3) NOT NULL,
	[C5_CCENCOS] [char](6) NOT NULL,
	[C5_CRFALMA] [char](4) NOT NULL,
	[C5_CGLOSA1] [char](30) NOT NULL,
	[C5_CGLOSA2] [char](30) NOT NULL,
	[C5_CGLOSA3] [char](30) NOT NULL,
	[C5_CTIPANE] [char](1) NOT NULL,
	[C5_CCODANE] [varchar](18) NOT NULL,
	[C5_DFECCRE] [datetime] NULL,
	[C5_CUSUCRE] [char](5) NOT NULL,
	[C5_DFECMOD] [datetime] NULL,
	[C5_CUSUMOD] [char](5) NOT NULL,
	[C5_CCODCLI] [char](18) NOT NULL,
	[C5_CNOMCLI] [char](50) NOT NULL,
	[C5_CRUC] [char](18) NOT NULL,
	[C5_CCODCAD] [char](4) NOT NULL,
	[C5_CCODINT] [char](10) NOT NULL,
	[C5_CCODTRA] [char](18) NOT NULL,
	[C5_CNOMTRA] [varchar](50) NOT NULL,
	[C5_CCODVEH] [char](18) NOT NULL,
	[C5_CTIPGUI] [char](2) NOT NULL,
	[C5_CSITGUI] [char](1) NOT NULL,
	[C5_CGUIFAC] [char](1) NOT NULL,
	[C5_CDESTIN] [char](4) NOT NULL,
	[C5_CDIRENV] [varchar](80) NOT NULL,
	[C5_CNUMORD] [char](20) NOT NULL,
	[C5_CTIPORD] [char](1) NOT NULL,
	[C5_CGUIDEV] [char](1) NOT NULL,
	[C5_CCODPRO] [char](18) NOT NULL,
	[C5_CNOMPRO] [varchar](50) NOT NULL,
	[C5_CCIAS] [char](4) NOT NULL,
	[C5_CFORVEN] [char](3) NOT NULL,
	[C5_CCODMON] [char](2) NOT NULL,
	[C5_CVENDE] [char](5) NOT NULL,
	[C5_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C5_CCODAGE] [char](4) NOT NULL,
	[C5_CNUMPED] [char](11) NOT NULL,
	[C5_CDIRECC] [varchar](80) NOT NULL,
	[C5_NIMPORT] [numeric](13, 2) NOT NULL,
	[C5_CTIPO] [char](1) NOT NULL,
	[C5_CSUBDIA] [char](4) NOT NULL,
	[C5_CCOMPRO] [char](6) NOT NULL,
	[C5_NPORDE1] [numeric](5, 2) NOT NULL,
	[C5_NPORDE2] [numeric](5, 2) NOT NULL,
	[C5_CTF] [char](2) NOT NULL,
	[C5_NFLETE] [numeric](9, 2) NOT NULL,
	[C5_CCODAUT] [varchar](15) NOT NULL,
	[C5_CRFTDO2] [char](2) NOT NULL,
	[C5_CRFNDO2] [char](24) NOT NULL,
	[C5_CNUMLIQ] [char](23) NOT NULL,
	[C5_CORDEN] [char](18) NOT NULL,
	[C5_CTIPOGS] [char](1) NOT NULL,
	[C5_DFECANU] [datetime] NULL,
	[C5_CCODFER] [char](18) NOT NULL,
	[C5_DFECEMB] [datetime] NULL,
	[C5_CGLOSA4] [char](50) NOT NULL,
	[C5_CVENDE2] [char](5) NOT NULL,
	[C5_CESTDEV] [char](1) NOT NULL,
	[C5_CEXTOR] [char](1) NOT NULL,
	[C5_CRENOM] [varchar](80) NOT NULL,
	[C5_CRERUC] [char](18) NOT NULL,
	[C5_CREREF] [varchar](80) NOT NULL,
	[C5_CDSNOM] [varchar](80) NOT NULL,
	[C5_CDSRUC] [char](18) NOT NULL,
	[C5_CLLECIU] [char](12) NOT NULL,
	[C5_CPARCIU] [char](12) NOT NULL,
	[C5_CTTRACT] [char](10) NOT NULL,
	[C5_CTRASRE] [char](10) NOT NULL,
	[C5_CTRAREM] [char](10) NOT NULL,
	[C5_CLICCON] [varchar](25) NOT NULL,
	[C5_CSBNOM] [varchar](80) NOT NULL,
	[C5_CSBRUC] [char](18) NOT NULL,
	[C5_CSBMTC] [varchar](25) NOT NULL,
	[C5_CMONPER] [char](2) NOT NULL,
	[C5_NIMPPER] [numeric](13, 2) NOT NULL,
	[C5_CFPERCP] [char](1) NOT NULL,
	[C5_CESTFIN] [char](1) NOT NULL,
	[C5_CFLGPEN] [char](1) NOT NULL,
	[C5_CTIPFOR] [char](2) NOT NULL,
	[C5_NPORPER] [numeric](8, 2) NOT NULL,
	[C5_CFLGTRM] [char](1) NOT NULL,
	[C5_USUDEL] [varchar](15) NULL,
	[C5_FECDEL] [datetime] NULL
) ON [PRIMARY]

-------------------------------------------------------------------
CREATE TABLE [dbo].[RS_ALMOVD0001](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[DFECDOC] [datetime] NULL,
	[CRFTDOC] [char](2) NULL,
	[CRFNDOC] [varchar](24) NULL,
	[CTIPMOV] [char](1) NULL,
	[CCODMOV] [char](2) NULL,
	[CCODIGO] [char](25) NULL,
	[CDESCRI] [varchar](50) NULL,
	[NCANTID] [numeric](11, 3) NULL,
	[NCANTIDPROV] [numeric](11, 3) NULL,
	[CCODPROV] [char](18) NULL,
	[CNOMPROV] [varchar](50) NULL,
	[UNIMED] [char](10) NULL,
	[CNUMORD] [varchar](20) NULL,
	[COLOR] [varchar](20) NULL,
	[LOTE] [varchar](15) NULL,
	[BULTOS] [int] NULL,
	[CONOS] [int] NULL,
	[KGNETO] [numeric](11, 3) NULL,
	[KGBRUTO] [numeric](11, 3) NULL,
	[KGNETOPROV] [numeric](11, 3) NULL,
	[KGBRUTOPROV] [numeric](11, 3) NULL,
	[TIPSERVICIO] [varchar](15) NULL,
	[CUBICACION] [char](4) NULL,
	[OBSERV] [text] NULL,
	[DETALLADO] [char](1) NULL,
	[VBCC] [char](1) NULL,
	[ESTADO] [char](1) NULL CONSTRAINT [DF_RS_ALMOVD_ESTADO0001]  DEFAULT ('V'),
	[CodTipoMov] [char](3) NULL,
	[NumPurOrd] [varchar](30) NULL,
	[NumEstilo] [varchar](30) NULL,
 CONSTRAINT [PK_RS_ALMOVD0001] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,
	[CTD] ASC,
	[CNUMDOC] ASC,
	[CITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[RS_ALMOVD0002](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[DFECDOC] [datetime] NULL,
	[CRFTDOC] [char](2) NULL,
	[CRFNDOC] [varchar](24) NULL,
	[CTIPMOV] [char](1) NULL,
	[CCODMOV] [char](2) NULL,
	[CCODIGO] [char](25) NULL,
	[CDESCRI] [varchar](50) NULL,
	[NCANTID] [numeric](11, 3) NULL,
	[NCANTIDPROV] [numeric](11, 3) NULL,
	[CCODPROV] [char](18) NULL,
	[CNOMPROV] [varchar](50) NULL,
	[UNIMED] [char](10) NULL,
	[CNUMORD] [varchar](20) NULL,
	[COLOR] [varchar](20) NULL,
	[LOTE] [varchar](15) NULL,
	[BULTOS] [int] NULL,
	[CONOS] [int] NULL,
	[KGNETO] [numeric](11, 3) NULL,
	[KGBRUTO] [numeric](11, 3) NULL,
	[KGNETOPROV] [numeric](11, 3) NULL,
	[KGBRUTOPROV] [numeric](11, 3) NULL,
	[TIPSERVICIO] [varchar](15) NULL,
	[CUBICACION] [char](4) NULL,
	[OBSERV] [text] NULL,
	[DETALLADO] [char](1) NULL,
	[VBCC] [char](1) NULL,
	[ESTADO] [char](1) NULL CONSTRAINT [DF_RS_ALMOVD_ESTADO002]  DEFAULT ('V'),
	[CodTipoMov] [char](3) NULL,
	[NumPurOrd] [varchar](30) NULL,
	[NumEstilo] [varchar](30) NULL,
 CONSTRAINT [PK_RS_ALMOVD0002] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,
	[CTD] ASC,
	[CNUMDOC] ASC,
	[CITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[RS_ALMOVD0006](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[DFECDOC] [datetime] NULL,
	[CRFTDOC] [char](2) NULL,
	[CRFNDOC] [varchar](24) NULL,
	[CTIPMOV] [char](1) NULL,
	[CCODMOV] [char](2) NULL,
	[CCODIGO] [char](25) NULL,
	[CDESCRI] [varchar](50) NULL,
	[NCANTID] [numeric](11, 3) NULL,
	[NCANTIDPROV] [numeric](11, 3) NULL,
	[CCODPROV] [char](18) NULL,
	[CNOMPROV] [varchar](50) NULL,
	[UNIMED] [char](10) NULL,
	[CNUMORD] [varchar](20) NULL,
	[COLOR] [varchar](20) NULL,
	[LOTE] [varchar](15) NULL,
	[BULTOS] [int] NULL,
	[CONOS] [int] NULL,
	[KGNETO] [numeric](11, 3) NULL,
	[KGBRUTO] [numeric](11, 3) NULL,
	[KGNETOPROV] [numeric](11, 3) NULL,
	[KGBRUTOPROV] [numeric](11, 3) NULL,
	[TIPSERVICIO] [varchar](15) NULL,
	[CUBICACION] [char](4) NULL,
	[OBSERV] [text] NULL,
	[DETALLADO] [char](1) NULL,
	[VBCC] [char](1) NULL,
	[ESTADO] [char](1) NULL CONSTRAINT [DF_RS_ALMOVD_ESTADO0006]  DEFAULT ('V'),
	[CodTipoMov] [char](3) NULL,
	[NumPurOrd] [varchar](30) NULL,
	[NumEstilo] [varchar](30) NULL,
 CONSTRAINT [PK_RS_ALMOVD0006] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,
	[CTD] ASC,
	[CNUMDOC] ASC,
	[CITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[RS_ALMOVD0008](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[DFECDOC] [datetime] NULL,
	[CRFTDOC] [char](2) NULL,
	[CRFNDOC] [varchar](24) NULL,
	[CTIPMOV] [char](1) NULL,
	[CCODMOV] [char](2) NULL,
	[CCODIGO] [char](25) NULL,
	[CDESCRI] [varchar](50) NULL,
	[NCANTID] [numeric](11, 3) NULL,
	[NCANTIDPROV] [numeric](11, 3) NULL,
	[CCODPROV] [char](18) NULL,
	[CNOMPROV] [varchar](50) NULL,
	[UNIMED] [char](10) NULL,
	[CNUMORD] [varchar](20) NULL,
	[COLOR] [varchar](20) NULL,
	[LOTE] [varchar](15) NULL,
	[BULTOS] [int] NULL,
	[CONOS] [int] NULL,
	[KGNETO] [numeric](11, 3) NULL,
	[KGBRUTO] [numeric](11, 3) NULL,
	[KGNETOPROV] [numeric](11, 3) NULL,
	[KGBRUTOPROV] [numeric](11, 3) NULL,
	[TIPSERVICIO] [varchar](15) NULL,
	[CUBICACION] [char](4) NULL,
	[OBSERV] [text] NULL,
	[DETALLADO] [char](1) NULL,
	[VBCC] [char](1) NULL,
	[ESTADO] [char](1) NULL CONSTRAINT [DF_RS_ALMOVD_ESTADO0008]  DEFAULT ('V'),
	[CodTipoMov] [char](3) NULL,
	[NumPurOrd] [varchar](30) NULL,
	[NumEstilo] [varchar](30) NULL,
 CONSTRAINT [PK_RS_ALMOVD0008] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,
	[CTD] ASC,
	[CNUMDOC] ASC,
	[CITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
------------------------------------------------------------------------------------

CREATE TABLE [dbo].[RS_ALMOVD_Del0001](
	[C6_CALMA] [char](4) NOT NULL,
	[C6_CTD] [char](2) NOT NULL,
	[C6_CNUMDOC] [char](11) NOT NULL,
	[C6_CITEM] [char](4) NOT NULL,
	[C6_CLOCALI] [char](4) NOT NULL,
	[C6_CCODIGO] [char](25) NOT NULL,
	[C6_NCANTID] [numeric](11, 3) NOT NULL,
	[C6_NCANTEN] [numeric](11, 3) NOT NULL,
	[C6_NCANFAC] [numeric](11, 3) NOT NULL,
	[C6_NPREUN1] [numeric](18, 9) NOT NULL,
	[C6_NPREUNI] [numeric](18, 9) NOT NULL,
	[C6_NMNPRUN] [numeric](18, 9) NOT NULL,
	[C6_NUSPRUN] [numeric](18, 9) NOT NULL,
	[C6_CSERIE] [char](18) NOT NULL,
	[C6_CSITUA] [char](1) NOT NULL,
	[C6_DFECDOC] [datetime] NULL,
	[C6_DFECVEN] [datetime] NULL,
	[C6_DFECENT] [datetime] NULL,
	[C6_CRFALMA] [char](4) NOT NULL,
	[C6_CTALLA] [char](1) NOT NULL,
	[C6_CESTADO] [char](1) NOT NULL,
	[C6_CCODMOV] [char](2) NOT NULL,
	[C6_CORDEN] [char](18) NOT NULL,
	[C6_NVALTOT] [numeric](13, 2) NOT NULL,
	[C6_NMNIMPO] [numeric](13, 2) NOT NULL,
	[C6_NUSIMPO] [numeric](13, 2) NOT NULL,
	[C6_CSUBDIA] [char](4) NOT NULL,
	[C6_CCOMPRO] [char](6) NOT NULL,
	[C6_CCODMON] [char](2) NOT NULL,
	[C6_CTIPO] [char](1) NOT NULL,
	[C6_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C6_NPREVTA] [numeric](11, 3) NOT NULL,
	[C6_CMONVTA] [char](2) NOT NULL,
	[C6_NUNXENV] [numeric](8, 3) NOT NULL,
	[C6_NNUMENV] [numeric](7, 2) NOT NULL,
	[C6_NDEVOL] [numeric](11, 3) NOT NULL,
	[C6_CCENCOS] [char](6) NOT NULL,
	[C6_CSOLI] [char](3) NOT NULL,
	[C6_NPRECIO] [numeric](18, 9) NOT NULL,
	[C6_NPRECI1] [numeric](18, 9) NOT NULL,
	[C6_NDESCTO] [numeric](11, 2) NOT NULL,
	[C6_NIGV] [numeric](11, 2) NOT NULL,
	[C6_NIGVPOR] [numeric](18, 0) NOT NULL,
	[C6_NIMPMN] [numeric](13, 2) NOT NULL,
	[C6_NIMPUS] [numeric](13, 2) NOT NULL,
	[C6_CDESCRI] [varchar](50) NOT NULL,
	[C6_NPORDE1] [numeric](6, 2) NOT NULL,
	[C6_NIMPO1] [numeric](10, 2) NOT NULL,
	[C6_NPORDE2] [numeric](6, 2) NOT NULL,
	[C6_NIMPO2] [numeric](10, 2) NOT NULL,
	[C6_NPORDE3] [numeric](6, 2) NOT NULL,
	[C6_NIMPO3] [numeric](10, 2) NOT NULL,
	[C6_NPORDE4] [numeric](6, 2) NOT NULL,
	[C6_NIMPO4] [numeric](10, 2) NOT NULL,
	[C6_NPORDE5] [numeric](6, 2) NOT NULL,
	[C6_NIMPO5] [numeric](10, 2) NOT NULL,
	[C6_NPORDES] [numeric](6, 2) NOT NULL,
	[C6_CTIPITM] [char](3) NOT NULL,
	[C6_CNUMPAQ] [char](4) NOT NULL,
	[C6_CCODLIN] [char](4) NOT NULL,
	[C6_CNROTAB] [char](6) NOT NULL,
	[C6_CNDSCF] [char](8) NOT NULL,
	[C6_CNDSCL] [char](8) NOT NULL,
	[C6_CNDSCA] [char](8) NOT NULL,
	[C6_CNDSCB] [char](8) NOT NULL,
	[C6_CNFLAT] [char](8) NOT NULL,
	[C6_NPESO] [numeric](10, 4) NOT NULL,
	[C6_CTR] [char](1) NOT NULL,
	[C6_NPRSIGV] [numeric](20, 9) NOT NULL,
	[C6_CTIPANE] [char](1) NOT NULL,
	[C6_CCODANE] [char](18) NOT NULL,
	[C6_CSTOCK] [char](1) NOT NULL,
	[C6_CCODAGE] [char](4) NOT NULL,
	[C6_CCODAUX] [char](25) NOT NULL,
	[C6_CITEREQ] [char](4) NOT NULL,
	[C6_CNROREQ] [char](7) NOT NULL,
	[C6_NTEMPER] [numeric](11, 2) NOT NULL,
	[C6_NISCPOR] [numeric](5, 2) NOT NULL,
	[C6_NISC] [numeric](11, 2) NOT NULL,
	[C6_CITEFAC] [char](4) NOT NULL,
	[C6_NCANRPE] [numeric](13, 3) NOT NULL,
	[C6_CNUMREQ] [char](7) NOT NULL,
	[C6_CITERQ] [char](4) NOT NULL,
	[C6_CCODRQ] [char](25) NOT NULL,
	[C6_DFECRQ] [datetime] NULL,
	[C6_CTIPPRO] [char](1) NOT NULL,
	[C6_NCANREQ] [numeric](11, 3) NOT NULL,
	[C6_CCTACMO] [char](12) NOT NULL,
	[C6_CNUMORD] [char](20) NOT NULL,
	[C6_CUMREF] [varchar](3) NOT NULL,
	[C6_NCANDEC] [numeric](18, 9) NOT NULL,
	[C6_NCANREF] [numeric](10, 2) NOT NULL,
	[C6_CITEMOC] [char](4) NULL,
	[C6_CVANEXO] [char](1) NULL,
	[C6_CVANEX2] [char](1) NULL,
	[C6_CCODAN2] [char](18) NULL,
	[C6_USUDEL] [varchar](15) NULL,
	[C6_FECDEL] [datetime] NULL
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[RS_ALMOVD_Del0002](
	[C6_CALMA] [char](4) NOT NULL,
	[C6_CTD] [char](2) NOT NULL,
	[C6_CNUMDOC] [char](11) NOT NULL,
	[C6_CITEM] [char](4) NOT NULL,
	[C6_CLOCALI] [char](4) NOT NULL,
	[C6_CCODIGO] [char](25) NOT NULL,
	[C6_NCANTID] [numeric](11, 3) NOT NULL,
	[C6_NCANTEN] [numeric](11, 3) NOT NULL,
	[C6_NCANFAC] [numeric](11, 3) NOT NULL,
	[C6_NPREUN1] [numeric](18, 9) NOT NULL,
	[C6_NPREUNI] [numeric](18, 9) NOT NULL,
	[C6_NMNPRUN] [numeric](18, 9) NOT NULL,
	[C6_NUSPRUN] [numeric](18, 9) NOT NULL,
	[C6_CSERIE] [char](18) NOT NULL,
	[C6_CSITUA] [char](1) NOT NULL,
	[C6_DFECDOC] [datetime] NULL,
	[C6_DFECVEN] [datetime] NULL,
	[C6_DFECENT] [datetime] NULL,
	[C6_CRFALMA] [char](4) NOT NULL,
	[C6_CTALLA] [char](1) NOT NULL,
	[C6_CESTADO] [char](1) NOT NULL,
	[C6_CCODMOV] [char](2) NOT NULL,
	[C6_CORDEN] [char](18) NOT NULL,
	[C6_NVALTOT] [numeric](13, 2) NOT NULL,
	[C6_NMNIMPO] [numeric](13, 2) NOT NULL,
	[C6_NUSIMPO] [numeric](13, 2) NOT NULL,
	[C6_CSUBDIA] [char](4) NOT NULL,
	[C6_CCOMPRO] [char](6) NOT NULL,
	[C6_CCODMON] [char](2) NOT NULL,
	[C6_CTIPO] [char](1) NOT NULL,
	[C6_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C6_NPREVTA] [numeric](11, 3) NOT NULL,
	[C6_CMONVTA] [char](2) NOT NULL,
	[C6_NUNXENV] [numeric](8, 3) NOT NULL,
	[C6_NNUMENV] [numeric](7, 2) NOT NULL,
	[C6_NDEVOL] [numeric](11, 3) NOT NULL,
	[C6_CCENCOS] [char](6) NOT NULL,
	[C6_CSOLI] [char](3) NOT NULL,
	[C6_NPRECIO] [numeric](18, 9) NOT NULL,
	[C6_NPRECI1] [numeric](18, 9) NOT NULL,
	[C6_NDESCTO] [numeric](11, 2) NOT NULL,
	[C6_NIGV] [numeric](11, 2) NOT NULL,
	[C6_NIGVPOR] [numeric](18, 0) NOT NULL,
	[C6_NIMPMN] [numeric](13, 2) NOT NULL,
	[C6_NIMPUS] [numeric](13, 2) NOT NULL,
	[C6_CDESCRI] [varchar](50) NOT NULL,
	[C6_NPORDE1] [numeric](6, 2) NOT NULL,
	[C6_NIMPO1] [numeric](10, 2) NOT NULL,
	[C6_NPORDE2] [numeric](6, 2) NOT NULL,
	[C6_NIMPO2] [numeric](10, 2) NOT NULL,
	[C6_NPORDE3] [numeric](6, 2) NOT NULL,
	[C6_NIMPO3] [numeric](10, 2) NOT NULL,
	[C6_NPORDE4] [numeric](6, 2) NOT NULL,
	[C6_NIMPO4] [numeric](10, 2) NOT NULL,
	[C6_NPORDE5] [numeric](6, 2) NOT NULL,
	[C6_NIMPO5] [numeric](10, 2) NOT NULL,
	[C6_NPORDES] [numeric](6, 2) NOT NULL,
	[C6_CTIPITM] [char](3) NOT NULL,
	[C6_CNUMPAQ] [char](4) NOT NULL,
	[C6_CCODLIN] [char](4) NOT NULL,
	[C6_CNROTAB] [char](6) NOT NULL,
	[C6_CNDSCF] [char](8) NOT NULL,
	[C6_CNDSCL] [char](8) NOT NULL,
	[C6_CNDSCA] [char](8) NOT NULL,
	[C6_CNDSCB] [char](8) NOT NULL,
	[C6_CNFLAT] [char](8) NOT NULL,
	[C6_NPESO] [numeric](10, 4) NOT NULL,
	[C6_CTR] [char](1) NOT NULL,
	[C6_NPRSIGV] [numeric](20, 9) NOT NULL,
	[C6_CTIPANE] [char](1) NOT NULL,
	[C6_CCODANE] [char](18) NOT NULL,
	[C6_CSTOCK] [char](1) NOT NULL,
	[C6_CCODAGE] [char](4) NOT NULL,
	[C6_CCODAUX] [char](25) NOT NULL,
	[C6_CITEREQ] [char](4) NOT NULL,
	[C6_CNROREQ] [char](7) NOT NULL,
	[C6_NTEMPER] [numeric](11, 2) NOT NULL,
	[C6_NISCPOR] [numeric](5, 2) NOT NULL,
	[C6_NISC] [numeric](11, 2) NOT NULL,
	[C6_CITEFAC] [char](4) NOT NULL,
	[C6_NCANRPE] [numeric](13, 3) NOT NULL,
	[C6_CNUMREQ] [char](7) NOT NULL,
	[C6_CITERQ] [char](4) NOT NULL,
	[C6_CCODRQ] [char](25) NOT NULL,
	[C6_DFECRQ] [datetime] NULL,
	[C6_CTIPPRO] [char](1) NOT NULL,
	[C6_NCANREQ] [numeric](11, 3) NOT NULL,
	[C6_CCTACMO] [char](12) NOT NULL,
	[C6_CNUMORD] [char](20) NOT NULL,
	[C6_CUMREF] [varchar](3) NOT NULL,
	[C6_NCANDEC] [numeric](18, 9) NOT NULL,
	[C6_NCANREF] [numeric](10, 2) NOT NULL,
	[C6_CITEMOC] [char](4) NULL,
	[C6_CVANEXO] [char](1) NULL,
	[C6_CVANEX2] [char](1) NULL,
	[C6_CCODAN2] [char](18) NULL,
	[C6_USUDEL] [varchar](15) NULL,
	[C6_FECDEL] [datetime] NULL
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[RS_ALMOVD_Del0006](
	[C6_CALMA] [char](4) NOT NULL,
	[C6_CTD] [char](2) NOT NULL,
	[C6_CNUMDOC] [char](11) NOT NULL,
	[C6_CITEM] [char](4) NOT NULL,
	[C6_CLOCALI] [char](4) NOT NULL,
	[C6_CCODIGO] [char](25) NOT NULL,
	[C6_NCANTID] [numeric](11, 3) NOT NULL,
	[C6_NCANTEN] [numeric](11, 3) NOT NULL,
	[C6_NCANFAC] [numeric](11, 3) NOT NULL,
	[C6_NPREUN1] [numeric](18, 9) NOT NULL,
	[C6_NPREUNI] [numeric](18, 9) NOT NULL,
	[C6_NMNPRUN] [numeric](18, 9) NOT NULL,
	[C6_NUSPRUN] [numeric](18, 9) NOT NULL,
	[C6_CSERIE] [char](18) NOT NULL,
	[C6_CSITUA] [char](1) NOT NULL,
	[C6_DFECDOC] [datetime] NULL,
	[C6_DFECVEN] [datetime] NULL,
	[C6_DFECENT] [datetime] NULL,
	[C6_CRFALMA] [char](4) NOT NULL,
	[C6_CTALLA] [char](1) NOT NULL,
	[C6_CESTADO] [char](1) NOT NULL,
	[C6_CCODMOV] [char](2) NOT NULL,
	[C6_CORDEN] [char](18) NOT NULL,
	[C6_NVALTOT] [numeric](13, 2) NOT NULL,
	[C6_NMNIMPO] [numeric](13, 2) NOT NULL,
	[C6_NUSIMPO] [numeric](13, 2) NOT NULL,
	[C6_CSUBDIA] [char](4) NOT NULL,
	[C6_CCOMPRO] [char](6) NOT NULL,
	[C6_CCODMON] [char](2) NOT NULL,
	[C6_CTIPO] [char](1) NOT NULL,
	[C6_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C6_NPREVTA] [numeric](11, 3) NOT NULL,
	[C6_CMONVTA] [char](2) NOT NULL,
	[C6_NUNXENV] [numeric](8, 3) NOT NULL,
	[C6_NNUMENV] [numeric](7, 2) NOT NULL,
	[C6_NDEVOL] [numeric](11, 3) NOT NULL,
	[C6_CCENCOS] [char](6) NOT NULL,
	[C6_CSOLI] [char](3) NOT NULL,
	[C6_NPRECIO] [numeric](18, 9) NOT NULL,
	[C6_NPRECI1] [numeric](18, 9) NOT NULL,
	[C6_NDESCTO] [numeric](11, 2) NOT NULL,
	[C6_NIGV] [numeric](11, 2) NOT NULL,
	[C6_NIGVPOR] [numeric](18, 0) NOT NULL,
	[C6_NIMPMN] [numeric](13, 2) NOT NULL,
	[C6_NIMPUS] [numeric](13, 2) NOT NULL,
	[C6_CDESCRI] [varchar](50) NOT NULL,
	[C6_NPORDE1] [numeric](6, 2) NOT NULL,
	[C6_NIMPO1] [numeric](10, 2) NOT NULL,
	[C6_NPORDE2] [numeric](6, 2) NOT NULL,
	[C6_NIMPO2] [numeric](10, 2) NOT NULL,
	[C6_NPORDE3] [numeric](6, 2) NOT NULL,
	[C6_NIMPO3] [numeric](10, 2) NOT NULL,
	[C6_NPORDE4] [numeric](6, 2) NOT NULL,
	[C6_NIMPO4] [numeric](10, 2) NOT NULL,
	[C6_NPORDE5] [numeric](6, 2) NOT NULL,
	[C6_NIMPO5] [numeric](10, 2) NOT NULL,
	[C6_NPORDES] [numeric](6, 2) NOT NULL,
	[C6_CTIPITM] [char](3) NOT NULL,
	[C6_CNUMPAQ] [char](4) NOT NULL,
	[C6_CCODLIN] [char](4) NOT NULL,
	[C6_CNROTAB] [char](6) NOT NULL,
	[C6_CNDSCF] [char](8) NOT NULL,
	[C6_CNDSCL] [char](8) NOT NULL,
	[C6_CNDSCA] [char](8) NOT NULL,
	[C6_CNDSCB] [char](8) NOT NULL,
	[C6_CNFLAT] [char](8) NOT NULL,
	[C6_NPESO] [numeric](10, 4) NOT NULL,
	[C6_CTR] [char](1) NOT NULL,
	[C6_NPRSIGV] [numeric](20, 9) NOT NULL,
	[C6_CTIPANE] [char](1) NOT NULL,
	[C6_CCODANE] [char](18) NOT NULL,
	[C6_CSTOCK] [char](1) NOT NULL,
	[C6_CCODAGE] [char](4) NOT NULL,
	[C6_CCODAUX] [char](25) NOT NULL,
	[C6_CITEREQ] [char](4) NOT NULL,
	[C6_CNROREQ] [char](7) NOT NULL,
	[C6_NTEMPER] [numeric](11, 2) NOT NULL,
	[C6_NISCPOR] [numeric](5, 2) NOT NULL,
	[C6_NISC] [numeric](11, 2) NOT NULL,
	[C6_CITEFAC] [char](4) NOT NULL,
	[C6_NCANRPE] [numeric](13, 3) NOT NULL,
	[C6_CNUMREQ] [char](7) NOT NULL,
	[C6_CITERQ] [char](4) NOT NULL,
	[C6_CCODRQ] [char](25) NOT NULL,
	[C6_DFECRQ] [datetime] NULL,
	[C6_CTIPPRO] [char](1) NOT NULL,
	[C6_NCANREQ] [numeric](11, 3) NOT NULL,
	[C6_CCTACMO] [char](12) NOT NULL,
	[C6_CNUMORD] [char](20) NOT NULL,
	[C6_CUMREF] [varchar](3) NOT NULL,
	[C6_NCANDEC] [numeric](18, 9) NOT NULL,
	[C6_NCANREF] [numeric](10, 2) NOT NULL,
	[C6_CITEMOC] [char](4) NULL,
	[C6_CVANEXO] [char](1) NULL,
	[C6_CVANEX2] [char](1) NULL,
	[C6_CCODAN2] [char](18) NULL,
	[C6_USUDEL] [varchar](15) NULL,
	[C6_FECDEL] [datetime] NULL
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[RS_ALMOVD_Del0008](
	[C6_CALMA] [char](4) NOT NULL,
	[C6_CTD] [char](2) NOT NULL,
	[C6_CNUMDOC] [char](11) NOT NULL,
	[C6_CITEM] [char](4) NOT NULL,
	[C6_CLOCALI] [char](4) NOT NULL,
	[C6_CCODIGO] [char](25) NOT NULL,
	[C6_NCANTID] [numeric](11, 3) NOT NULL,
	[C6_NCANTEN] [numeric](11, 3) NOT NULL,
	[C6_NCANFAC] [numeric](11, 3) NOT NULL,
	[C6_NPREUN1] [numeric](18, 9) NOT NULL,
	[C6_NPREUNI] [numeric](18, 9) NOT NULL,
	[C6_NMNPRUN] [numeric](18, 9) NOT NULL,
	[C6_NUSPRUN] [numeric](18, 9) NOT NULL,
	[C6_CSERIE] [char](18) NOT NULL,
	[C6_CSITUA] [char](1) NOT NULL,
	[C6_DFECDOC] [datetime] NULL,
	[C6_DFECVEN] [datetime] NULL,
	[C6_DFECENT] [datetime] NULL,
	[C6_CRFALMA] [char](4) NOT NULL,
	[C6_CTALLA] [char](1) NOT NULL,
	[C6_CESTADO] [char](1) NOT NULL,
	[C6_CCODMOV] [char](2) NOT NULL,
	[C6_CORDEN] [char](18) NOT NULL,
	[C6_NVALTOT] [numeric](13, 2) NOT NULL,
	[C6_NMNIMPO] [numeric](13, 2) NOT NULL,
	[C6_NUSIMPO] [numeric](13, 2) NOT NULL,
	[C6_CSUBDIA] [char](4) NOT NULL,
	[C6_CCOMPRO] [char](6) NOT NULL,
	[C6_CCODMON] [char](2) NOT NULL,
	[C6_CTIPO] [char](1) NOT NULL,
	[C6_NTIPCAM] [numeric](11, 4) NOT NULL,
	[C6_NPREVTA] [numeric](11, 3) NOT NULL,
	[C6_CMONVTA] [char](2) NOT NULL,
	[C6_NUNXENV] [numeric](8, 3) NOT NULL,
	[C6_NNUMENV] [numeric](7, 2) NOT NULL,
	[C6_NDEVOL] [numeric](11, 3) NOT NULL,
	[C6_CCENCOS] [char](6) NOT NULL,
	[C6_CSOLI] [char](3) NOT NULL,
	[C6_NPRECIO] [numeric](18, 9) NOT NULL,
	[C6_NPRECI1] [numeric](18, 9) NOT NULL,
	[C6_NDESCTO] [numeric](11, 2) NOT NULL,
	[C6_NIGV] [numeric](11, 2) NOT NULL,
	[C6_NIGVPOR] [numeric](18, 0) NOT NULL,
	[C6_NIMPMN] [numeric](13, 2) NOT NULL,
	[C6_NIMPUS] [numeric](13, 2) NOT NULL,
	[C6_CDESCRI] [varchar](50) NOT NULL,
	[C6_NPORDE1] [numeric](6, 2) NOT NULL,
	[C6_NIMPO1] [numeric](10, 2) NOT NULL,
	[C6_NPORDE2] [numeric](6, 2) NOT NULL,
	[C6_NIMPO2] [numeric](10, 2) NOT NULL,
	[C6_NPORDE3] [numeric](6, 2) NOT NULL,
	[C6_NIMPO3] [numeric](10, 2) NOT NULL,
	[C6_NPORDE4] [numeric](6, 2) NOT NULL,
	[C6_NIMPO4] [numeric](10, 2) NOT NULL,
	[C6_NPORDE5] [numeric](6, 2) NOT NULL,
	[C6_NIMPO5] [numeric](10, 2) NOT NULL,
	[C6_NPORDES] [numeric](6, 2) NOT NULL,
	[C6_CTIPITM] [char](3) NOT NULL,
	[C6_CNUMPAQ] [char](4) NOT NULL,
	[C6_CCODLIN] [char](4) NOT NULL,
	[C6_CNROTAB] [char](6) NOT NULL,
	[C6_CNDSCF] [char](8) NOT NULL,
	[C6_CNDSCL] [char](8) NOT NULL,
	[C6_CNDSCA] [char](8) NOT NULL,
	[C6_CNDSCB] [char](8) NOT NULL,
	[C6_CNFLAT] [char](8) NOT NULL,
	[C6_NPESO] [numeric](10, 4) NOT NULL,
	[C6_CTR] [char](1) NOT NULL,
	[C6_NPRSIGV] [numeric](20, 9) NOT NULL,
	[C6_CTIPANE] [char](1) NOT NULL,
	[C6_CCODANE] [char](18) NOT NULL,
	[C6_CSTOCK] [char](1) NOT NULL,
	[C6_CCODAGE] [char](4) NOT NULL,
	[C6_CCODAUX] [char](25) NOT NULL,
	[C6_CITEREQ] [char](4) NOT NULL,
	[C6_CNROREQ] [char](7) NOT NULL,
	[C6_NTEMPER] [numeric](11, 2) NOT NULL,
	[C6_NISCPOR] [numeric](5, 2) NOT NULL,
	[C6_NISC] [numeric](11, 2) NOT NULL,
	[C6_CITEFAC] [char](4) NOT NULL,
	[C6_NCANRPE] [numeric](13, 3) NOT NULL,
	[C6_CNUMREQ] [char](7) NOT NULL,
	[C6_CITERQ] [char](4) NOT NULL,
	[C6_CCODRQ] [char](25) NOT NULL,
	[C6_DFECRQ] [datetime] NULL,
	[C6_CTIPPRO] [char](1) NOT NULL,
	[C6_NCANREQ] [numeric](11, 3) NOT NULL,
	[C6_CCTACMO] [char](12) NOT NULL,
	[C6_CNUMORD] [char](20) NOT NULL,
	[C6_CUMREF] [varchar](3) NOT NULL,
	[C6_NCANDEC] [numeric](18, 9) NOT NULL,
	[C6_NCANREF] [numeric](10, 2) NOT NULL,
	[C6_CITEMOC] [char](4) NULL,
	[C6_CVANEXO] [char](1) NULL,
	[C6_CVANEX2] [char](1) NULL,
	[C6_CCODAN2] [char](18) NULL,
	[C6_USUDEL] [varchar](15) NULL,
	[C6_FECDEL] [datetime] NULL
) ON [PRIMARY]

GO
-----------------------------------------------------------------------------

CREATE TABLE [dbo].[RS_ALMOVD_TALLA0001](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[TALLA] [char](10) NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[ORDEN] [int] NULL,
 CONSTRAINT [PK_RS_ALMOVD_TALLA0001] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,[CTD] ASC,[CNUMDOC] ASC,[CITEM] ASC,[TALLA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[RS_ALMOVD_TALLA0002](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[TALLA] [char](10) NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[ORDEN] [int] NULL,
 CONSTRAINT [PK_RS_ALMOVD_TALLA0002] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,[CTD] ASC,[CNUMDOC] ASC,[CITEM] ASC,[TALLA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
create TABLE [dbo].[RS_ALMOVD_TALLA0006](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[TALLA] [char](10) NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[ORDEN] [int] NULL,
 CONSTRAINT [PK_RS_ALMOVD_TALLA0006] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,[CTD] ASC,[CNUMDOC] ASC,[CITEM] ASC,[TALLA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
create TABLE [dbo].[RS_ALMOVD_TALLA0008](
	[CALMA] [char](4) NOT NULL,
	[CTD] [char](2) NOT NULL,
	[CNUMDOC] [char](11) NOT NULL,
	[CITEM] [char](4) NOT NULL,
	[TALLA] [char](10) NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[ORDEN] [int] NULL,
 CONSTRAINT [PK_RS_ALMOVD_TALLA0008] PRIMARY KEY CLUSTERED 
(
	[CALMA] ASC,[CTD] ASC,[CNUMDOC] ASC,[CITEM] ASC,[TALLA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
---------------------------------------------------------------

CREATE TABLE [dbo].[RS_MOVENTCONTEO0001](
	[IdMovimiento] [int] NOT NULL,
	[CodProv] [char](15) NULL,
	[Fecha] [datetime] NOT NULL,
	[PO] [varchar](25) NOT NULL,
	[Estilo] [varchar](25) NOT NULL,
	[Color] [varchar](20) NOT NULL,
	[DocRef] [varchar](25) NULL,
	[Cantidad] [int] NOT NULL,
	[CantPrimera] [int] NULL,
	[CantSegunda] [int] NULL,
	[CantTercera] [int] NULL,
	[Observacion] [varchar](1000) NULL,
 CONSTRAINT [PK_RS_MOVENTCONTEO0001] PRIMARY KEY CLUSTERED 
(
	[IdMovimiento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RS_MOVENTCONTEO0002](
	[IdMovimiento] [int] NOT NULL,
	[CodProv] [char](15) NULL,
	[Fecha] [datetime] NOT NULL,
	[PO] [varchar](25) NOT NULL,
	[Estilo] [varchar](25) NOT NULL,
	[Color] [varchar](20) NOT NULL,
	[DocRef] [varchar](25) NULL,
	[Cantidad] [int] NOT NULL,
	[CantPrimera] [int] NULL,
	[CantSegunda] [int] NULL,
	[CantTercera] [int] NULL,
	[Observacion] [varchar](1000) NULL,
 CONSTRAINT [PK_RS_MOVENTCONTEO0002] PRIMARY KEY CLUSTERED 
(
	[IdMovimiento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[RS_MOVENTCONTEO0006](
	[IdMovimiento] [int] NOT NULL,
	[CodProv] [char](15) NULL,
	[Fecha] [datetime] NOT NULL,
	[PO] [varchar](25) NOT NULL,
	[Estilo] [varchar](25) NOT NULL,
	[Color] [varchar](20) NOT NULL,
	[DocRef] [varchar](25) NULL,
	[Cantidad] [int] NOT NULL,
	[CantPrimera] [int] NULL,
	[CantSegunda] [int] NULL,
	[CantTercera] [int] NULL,
	[Observacion] [varchar](1000) NULL,
 CONSTRAINT [PK_RS_MOVENTCONTEO0006] PRIMARY KEY CLUSTERED 
(
	[IdMovimiento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[RS_MOVENTCONTEO0008](
	[IdMovimiento] [int] NOT NULL,
	[CodProv] [char](15) NULL,
	[Fecha] [datetime] NOT NULL,
	[PO] [varchar](25) NOT NULL,
	[Estilo] [varchar](25) NOT NULL,
	[Color] [varchar](20) NOT NULL,
	[DocRef] [varchar](25) NULL,
	[Cantidad] [int] NOT NULL,
	[CantPrimera] [int] NULL,
	[CantSegunda] [int] NULL,
	[CantTercera] [int] NULL,
	[Observacion] [varchar](1000) NULL,
 CONSTRAINT [PK_RS_MOVENTCONTEO0008] PRIMARY KEY CLUSTERED 
(
	[IdMovimiento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[AL_TiposMov0001](
	[CodTipoMov] [char](3) NOT NULL,
	[DesTipoMov] [varchar](50) NOT NULL,
	[CodClaseMov] [char](1) NOT NULL,
	[TipoAccion] [char](1) NOT NULL,
	[MovCorte] [char](1) NOT NULL,
	[Estado] [char](1) NOT NULL  DEFAULT ('A'),
	[FecCreacion] [datetime] NOT NULL,
	[UsuCreacion] [varchar](15) NOT NULL,
 CONSTRAINT [PK_AL_TiposMov0001] PRIMARY KEY CLUSTERED 
(
	[CodTipoMov] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[AL_TiposMov0002](
	[CodTipoMov] [char](3) NOT NULL,
	[DesTipoMov] [varchar](50) NOT NULL,
	[CodClaseMov] [char](1) NOT NULL,
	[TipoAccion] [char](1) NOT NULL,
	[MovCorte] [char](1) NOT NULL,
	[Estado] [char](1) NOT NULL  DEFAULT ('A'),
	[FecCreacion] [datetime] NOT NULL,
	[UsuCreacion] [varchar](15) NOT NULL,
 CONSTRAINT [PK_AL_TiposMov0002] PRIMARY KEY CLUSTERED 
(
	[CodTipoMov] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[AL_TiposMov0006](
	[CodTipoMov] [char](3) NOT NULL,
	[DesTipoMov] [varchar](50) NOT NULL,
	[CodClaseMov] [char](1) NOT NULL,
	[TipoAccion] [char](1) NOT NULL,
	[MovCorte] [char](1) NOT NULL,
	[Estado] [char](1) NOT NULL  DEFAULT ('A'),
	[FecCreacion] [datetime] NOT NULL,
	[UsuCreacion] [varchar](15) NOT NULL,
 CONSTRAINT [PK_AL_TiposMov0006] PRIMARY KEY CLUSTERED 
(
	[CodTipoMov] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[AL_TiposMov0008](
	[CodTipoMov] [char](3) NOT NULL,
	[DesTipoMov] [varchar](50) NOT NULL,
	[CodClaseMov] [char](1) NOT NULL,
	[TipoAccion] [char](1) NOT NULL,
	[MovCorte] [char](1) NOT NULL,
	[Estado] [char](1) NOT NULL  DEFAULT ('A'),
	[FecCreacion] [datetime] NOT NULL,
	[UsuCreacion] [varchar](15) NOT NULL,
 CONSTRAINT [PK_AL_TiposMov0008] PRIMARY KEY CLUSTERED 
(
	[CodTipoMov] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

go
insert into AL_TiposMov0001
select * from modelador..AL_TiposMov 
go
insert into AL_TiposMov0002
select * from modelador..AL_TiposMov  
go
insert into AL_TiposMov0006
select * from modelador..AL_TiposMov 
go
insert into AL_TiposMov0008
select * from modelador..AL_TiposMov 
go
--delete rs_almovC0001
insert into RS_ALMOVC0001
select * from modelador..RS_ALMOVC
go
--delete rs_almovd0001
insert into RS_ALMOVD0001
select * from modelador..RS_ALMOVD
go
delete RS_ALMOVD_TALLA0001
insert into RS_ALMOVD_TALLA0001
select * from modelador..RS_ALMOVD_TALLA 

ALTER TABLE [dbo].[RS_ALMOVD_TALLA0001]  
drop CONSTRAINT [FK_RS_ALMOVD_TALLA_RS_ALMOVD0001] 