--DROP TABLE COSTEO
create table COSTEO (
[ID]	CHAR(10) NOT NULL ,
ALMA	CHAR(4)	 NOT NULL DEFAULT '',
CTD		CHAR(2)	 NOT NULL DEFAULT '',
NUMDOC	CHAR(11) NOT NULL,
ITEM	CHAR(4)  NOT NULL DEFAULT '0001',
CODIGO	CHAR(25) NOT NULL,
LIN		CHAR(2)	 NOT NULL DEFAULT '01',
PO		CHAR(25) NOT NULL,
COLOR	VARCHAR(30) NOT NULL DEFAULT '',
CORTE	CHAR(12) NOT NULL DEFAULT '',
CANTI	NUMERIC (18,3) NOT NULL DEFAULT 0,
MONEDA	CHAR(2) NOT NULL DEFAULT 'MN',
PRECIO	NUMERIC(18,2) NOT NULL DEFAULT 0,
TIPCAM	NUMERIC(10,3) NOT NULL DEFAULT 0,
SOLTOT	NUMERIC(18,3) NOT NULL DEFAULT 0,
FECHA	SMALLDATETIME NOT NULL DEFAULT GETDATE(),
USUARIO CHAR(4)  NOT NULL,
ESTADO  CHAR(1)  NOT NULL DEFAULT 'A',
 CONSTRAINT [PK_COSTEEO] PRIMARY KEY CLUSTERED 
(
	[ID]		ASC,
	[ALMA]		ASC,
	[CTD]		ASC,
	[NUMDOC]	ASC,
	[ITEM]		ASC,
	[CODIGO]	ASC,
	[LIN]		ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

