
Update RSFACCAR..AL0001ARTI Set AR_CDESCRI='TELA PLANA 50/1 MODAL 100% COLOR CREMA',
AR_CDESCR2='mande ud',AR_CCODIG2='promo 3x2',AR_CUNIDAD='KGR',AR_CCUENTA='241102 '  ,   
AR_NPRECI1=0,AR_NPRECI2=0,AR_NPRECI3=0,AR_NPRECI4=0,AR_NPRECI5=0,AR_NPRECI6=0,
AR_CMONVTA='US',AR_NIGVPOR=18,AR_NISCPOR=0,AR_NIGVCPR=18,AR_NPERC1=0,AR_NPERC2=0,AR_NDETRA=0,
AR_CFLGRCN='s',AR_NTASRCN=0,AR_CTIPO='N',AR_CTIPDES='',AR_NDESCTO=0,AR_NPDIS=0,AR_NPCOM=0,AR_CGRUPO='TL',
AR_CFAMILI='MP',AR_CTIPEXI='03',AR_CMODELO='TFMOD',AR_CMARCA='MAT PRIM',
AR_CANOFAB='1900',AR_CLUGORI='01',AR_CLINEA='0001',AR_NPESO=2,AR_NVOLUME=10,AR_NAREA=0,AR_CMEDIDA='',AR_CANNO='1900',
AR_CGROSOR='22',AR_NFACTOR=60,
AR_NANCHO=0,AR_NLARGO=0,AR_CMONCOM='MN',AR_NPRECOM=0,AR_DFECCOM=Null,AR_CCODPRO='  ',
AR_CMONFOB='US',AR_NPREFOB=0,
AR_CCLAART='TL ',AR_CPARARA='sin pàrtida', AR_CCATEGO='',AR_TOBSERV='',AR_CUNIREF='BLS',
AR_NFACREF=10,AR_CTIPOI='S',AR_CFUNIRE='S',AR_CFSTOCK='S',AR_CFDECI='S',AR_CFPRELI='S',AR_CFRESTA='N',
AR_CFSERIE='S',AR_CFLOTE='S',AR_CESTADO='V',AR_NLONSER=5,AR_CUSUMOD='sist',
AR_DFECMOD=Convert(datetime,'04/03/2014 00:00:00',103),AR_CDISENO='',
AR_CMEDNEU='S',AR_CINDCAR='S',AR_CCOLOR='SSS',AR_CTALLA='SSSS',
AR_NMARVTA='0' 
Where AR_CCODIGO='0000010204001000'













/*
Update W2118341 Set AV_CCODART='0000010204001000         '
Delete From RSFACCAR..AL0001AADV Where AV_CCODART='0000010204001000         '
Insert Into RSFACCAR..AL0001AADV Select * From W2118341
Select AR_CFVEHI From RSFACCAR..AL0001ARTI Where AR_CCODIGO='0000010204001000'
Select AR_CCODIGO As CadeBus,AR_CCODIGO As CadeBus2,AR_CCODIGO,AR_CDESCRI,AR_CMONVTA,AR_NPRECI1,AR_NPRECI2,AR_NIGVPOR,AR_CCUENTA,AR_NIMAGEN From RSFACCAR..AL0001ARTI Order by AR_CCODIGO
Drop Table W2118341
Select TG_CCLAVE From RSFACCAR..AL0001TABL Where TG_CCOD='00' AND TG_CCLAVE='M1'
Select TG_CCLAVE From RSFACCAR..AL0001TABL Where TG_CCOD='00' AND TG_CCLAVE='M2'
Select TG_CCLAVE From RSFACCAR..AL0001TABL Where TG_CCOD='00' AND TG_CCLAVE='M3'
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='03' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='05' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='08' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='06' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='38' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='T1' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='39' Order by TG_CCLAVE
Select TC_CEXISTE,TC_CDESCRI From RSFACCAR..FT0001CTAE Order by TC_CEXISTE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='05' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='03' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='15' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='36' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='03' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='87' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='03' Order by TG_CCLAVE
Select TG_CCLAVE From RSFACCAR..AL0001TABL Where TG_CCOD='00' AND TG_CCLAVE='M1'
Select TG_CCLAVE From RSFACCAR..AL0001TABL Where TG_CCOD='00' AND TG_CCLAVE='M2'
Select TG_CCLAVE From RSFACCAR..AL0001TABL Where TG_CCOD='00' AND TG_CCLAVE='M3'
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='V7' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001TABL Where TG_CCOD='V6' Order by TG_CCLAVE
Select * From RSFACCAR..AL0001ARTI Where AR_CCODIGO='0000010204001000         '
union
Select * From RSFACCAR..AL0001ARTI Where AR_CCODIGO = ' '
order by AR_CCODIGO desc
--insert into  RSFACCAR..AL0008ARTI (ar_ccodigo, ar_cdescri, ar_cunidad, ar_ccuenta)
values (' ','','','')

Select LI_CDESLIN From RSFACCAR..FT0001LINE Where LI_CCODLIN='    '
Select AC_CNOMBRE From RSCONCAR..CP0001MAES Where AC_CVANEXO='P' AND AC_CCODIGO='                  '
Drop Table W2118341
Create Table RSFACCAR..W9554668(AV_CCODPAI [char](4) NOT NULL Default '',AV_CCODART [char](25) NOT NULL Default '',AV_CPARARA [varchar](15) NOT NULL Default '',AV_NADVPOR [numeric](9,4) NOT 
NULL Default 0,AV_CESTADO [char](1) NOT NULL Default '',AV_CUSUCRE [char](5) NOT NULL Default '',AV_CUSUMOD [char](5) NOT NULL Default '',AV_DFECCRE [datetime],AV_DFECMOD 
[datetime],AV_NPREFOB [numeric](18,9) NOT NULL Default 0,AV_NPRECIF [numeric](18,9) NOT NULL Default 0,AV_CMONFOB [char](2) NOT NULL Default '',AV_CMONCIF [char](2) NOT NULL Default '')
Insert Into W9554668 Select * From RSFACCAR..AL0001AADV Where AV_CCODART='0000010204001000         '
Select A.AV_CCODPAI As CadeBus,A.*,B.TG_CDESCRI As NombDistri From W9554668 A Left Join RSFACCAR..AL0001TABL B  On B.TG_CCOD='27' And LTRIM(RTRIM(B.TG_CCLAVE))=A.AV_CCODPAI Order by 
AV_CCODPAI
Select PCUENTA,PDESCRI From RSCONCAR..CT0001PLEM Where PVTIPCTA<>'X' AND PCUENTA='241102      ' 
Update RSFACCAR..AL0001ARTI Set AR_CDESCRI='TELA PLANA 50/1 MODAL 100% COLOR CREMA',AR_CDESCR2='descripcion 2',AR_CCODIG2='codigo refeencia',AR_CUNIDAD='KGR',AR_CCUENTA='241102      
',AR_NPRECI1=0,AR_NPRECI2=0,AR_NPRECI3=0,AR_NPRECI4=0,AR_NPRECI5=0,AR_NPRECI6=0,AR_CMONVTA='US',AR_NIGVPOR=18,AR_NISCPOR=0,AR_NIGVCPR=18,AR_NPERC1=0,AR_NPERC2=0,AR_NDETRA=0,AR_CFLGRCN='N',AR_NTASRCN=0,AR_CTIPO='N',AR_CTIPDES='',AR_NDESCTO=0,AR_NPDIS=0,AR_NPCOM=0,AR_CGRUPO='TL          
',AR_CFAMILI='MP          ',AR_CTIPEXI='03          ',AR_CMODELO='TFMOD       ',AR_CMARCA='MAT 
PRIM',AR_CANOFAB='',AR_CLUGORI='',AR_CLINEA='',AR_NPESO=0,AR_NVOLUME=0,AR_NAREA=0,AR_CMEDIDA='      ',AR_CANNO='         ',AR_CGROSOR='               
',AR_NFACTOR=0,AR_NANCHO=0,AR_NLARGO=0,AR_CMONCOM='MN',AR_NPRECOM=0,AR_DFECCOM=Null,AR_CCODPRO='                  ',AR_CMONFOB='US',AR_NPREFOB=0,AR_CCLAART='TL ',AR_CPARARA='sin 
pàrtida',AR_CCATEGO='',AR_TOBSERV='',AR_CUNIREF='',AR_NFACREF=0,AR_CTIPOI='N',AR_CFUNIRE='N',AR_CFSTOCK='S',AR_CFDECI='S',AR_CFPRELI='S',AR_CFRESTA='N',AR_CFSERIE='N',AR_CFLOTE='S',AR_CESTADO='V',AR_NLONSER=0,AR_CUSUMOD='sist 
',AR_DFECMOD=Convert(datetime,'04/03/2014 00:00:00',103),AR_CDISENO='',AR_CMEDNEU='',AR_CINDCAR='',AR_CCOLOR='',AR_CTALLA='',AR_NMARVTA='0' Where AR_CCODIGO='0000010204001000         '
Create Table RSFACCAR..W2102711(AV_CCODPAI [char](4) NOT NULL Default '',AV_CCODART [char](25) NOT NULL Default '',AV_CPARARA [varchar](15) NOT NULL Default '',AV_NADVPOR [numeric](9,4) NOT 
NULL Default 0,AV_CESTADO [char](1) NOT NULL Default '',AV_CUSUCRE [char](5) NOT NULL Default '',AV_CUSUMOD [char](5) NOT NULL Default '',AV_DFECCRE [datetime],AV_DFECMOD 
[datetime],AV_NPREFOB [numeric](18,9) NOT NULL Default 0,AV_NPRECIF [numeric](18,9) NOT NULL Default 0,AV_CMONFOB [char](2) NOT NULL Default '',AV_CMONCIF [char](2) NOT NULL Default '')
Insert Into W2102711 Select * From RSFACCAR..AL0001AADV Where AV_CCODART='0000010204001000         '
Select A.AV_CCODPAI As CadeBus,A.*,B.TG_CDESCRI As NombDistri From W2102711 A Left Join RSFACCAR..AL0001TABL B  On B.TG_CCOD='27' And LTRIM(RTRIM(B.TG_CCLAVE))=A.AV_CCODPAI Order by 
AV_CCODPAI
Update RSFACCAR..AL0001ARTI Set AR_CDESCRI='TELA PLANA 50/1 MODAL 100% COLOR CREMA',AR_CDESCR2='descripcion 2',AR_CCODIG2='codigo refeencia',AR_CUNIDAD='KGR',AR_CCUENTA='241102      
',AR_NPRECI1=0,AR_NPRECI2=0,AR_NPRECI3=0,AR_NPRECI4=0,AR_NPRECI5=0,AR_NPRECI6=0,AR_CMONVTA='US',AR_NIGVPOR=18,AR_NISCPOR=0,AR_NIGVCPR=18,AR_NPERC1=0,AR_NPERC2=0,AR_NDETRA=0,AR_CFLGRCN='N',AR_NTASRCN=0,AR_CTIPO='N',AR_CTIPDES='',AR_NDESCTO=0,AR_NPDIS=0,AR_NPCOM=0,AR_CGRUPO='TL          
',AR_CFAMILI='MP          ',AR_CTIPEXI='03          ',AR_CMODELO='TFMOD       ',AR_CMARCA='MAT 
PRIM',AR_CANOFAB='',AR_CLUGORI='',AR_CLINEA='',AR_NPESO=0,AR_NVOLUME=0,AR_NAREA=0,AR_CMEDIDA='      ',AR_CANNO='         ',AR_CGROSOR='               
',AR_NFACTOR=0,AR_NANCHO=0,AR_NLARGO=0,AR_CMONCOM='MN',AR_NPRECOM=9.99,AR_DFECCOM=Convert(datetime,'01/01/2001',103),AR_CCODPRO='20100174911       
',AR_CMONFOB='US',AR_NPREFOB=0.0001,AR_CCLAART='TL ',AR_CPARARA='sin 
pàrtida',AR_CCATEGO='',AR_TOBSERV='',AR_CUNIREF='',AR_NFACREF=0,AR_CTIPOI='N',AR_CFUNIRE='N',AR_CFSTOCK='S',AR_CFDECI='S',AR_CFPRELI='S',AR_CFRESTA='N',AR_CFSERIE='N',AR_CFLOTE='S',AR_CESTADO='V',AR_NLONSER=0,AR_CUSUMOD='sist 
',AR_DFECMOD=Convert(datetime,'04/03/2014 00:00:00',103),AR_CDISENO='',AR_CMEDNEU='',AR_CINDCAR='',AR_CCOLOR='',AR_CTALLA='',AR_NMARVTA='0' Where AR_CCODIGO='0000010204001000         '
Update W2102711 Set AV_CCODART='0000010204001000         '
Delete From RSFACCAR..AL0001AADV Where AV_CCODART='0000010204001000         '
Insert Into RSFACCAR..AL0001AADV Select * From W2102711








*/