--select * from [USR-OPC] 
--WHERE USUARIO = 'mhd'

INSERT INTO SUBMENU SELECT '02','03', 'ACABADOS', 'ACABADOS.ASP','A'
INSERT INTO [USR-OPC] SELECT 'SIST', '02', '03', NULL
INSERT INTO [USR-OPC] SELECT 'MHD', '02', '03', NULL
INSERT INTO [USR-OPC] SELECT 'BET', '02', '03', NULL
DELETE [USR-OPC] WHERE USUARIO = 'BET' and MENU in ('01','03' ,'06')