Select 
A.C6_CALMA,A.C6_CLOCALI,A.C6_CTD,'',A.C6_CNUMDOC,A.C6_CITEM,Upper(A.C6_CCODIGO),B.AR_CCUENTA,B.AR_CCUENTR,B.AR_CGRUPO,B.AR_CMODELO,B.AR_CFAMILI,B.AR_CMARCA,B.AR_CLUGORI,B.AR_CANOFAB,B.AR_CLINEA,A.C6_NCANTID,A.C6_NPREUNI,A.C6_CSERIE,A.C6_DFECDOC,A.C6_CCENCOS,A.C6_CCODMOV,A.C6_CORDEN,A.C6_NVALTOT,A.C6_CSUBDIA,A.C6_CCOMPRO,A.C6_CCODMON,A.C6_CSTOCK,'',A.C6_CTIPO,A.C6_NTIPCAM,A.C6_CSOLI,A.C6_CTIPANE,A.C6_CCODANE,A.C6_NMNIMPO,A.C6_NUSIMPO,A.C6_NMNPRUN,A.C6_NUSPRUN,A.C6_CCTACMO, 
Case When C.C5_CCODMOV='08' Then    Case When C.C5_CCODMON = 'US' Then Abs(A.C6_NIMPMN) - (Abs(A.C6_NIGV) * 
C.C5_NTIPCAM) Else Abs(A.C6_NIMPMN) - Abs(A.C6_NIGV) End Else 0 End, Case When C.C5_CCODMOV='08' Then    
Case When C.C5_NTIPCAM=0       Then Case When C.C5_CCODMON = 'US' Then Abs(A.C6_NIMPUS) - Abs(A.C6_NIGV) 
Else Abs(A.C6_NIMPUS) - (Abs(A.C6_NIGV)/1) End       Else Case When C.C5_CCODMON = 'US' Then 
Abs(A.C6_NIMPUS) - Abs(A.C6_NIGV) Else Abs(A.C6_NIMPUS) - (Abs(A.C6_NIGV)/C.C5_NTIPCAM) End     End  Else 0 
End,  '','','','','','','','','','','','',''  From RSFACCAR..AL0001MOVD A Inner Join RSFACCAR..AL0001ARTI B 
On B.AR_CCODIGO=A.C6_CCODIGO Inner Join RSFACCAR..AL0001TABM On TM_CTIPMOV=RIGHT(A.C6_CTD,1) And 
TM_CCODMOV=A.C6_CCODMOV  Inner Join RSFACCAR..AL0001ALMA On A1_CALMA=A.C6_CALMA  Inner Join 
RSFACCAR..AL0001MOVC C On C.C5_CLOCALI=A.C6_CLOCALI And C.C5_CALMA=A.C6_CALMA And C.C5_CTD=A.C6_CTD And 
C.C5_CNUMDOC=A.C6_CNUMDOC  Where  A.C6_CCODMOV<>'01' And 
A.C6_CCODMOV<>'03' And A.C6_CTR<>'T' And A.C6_CSITUA<>'A' And (TM_CTIPCOS<>'N' And A1_CCOSTO<>'N' And 
Rtrim(AR_CTIPOI)<>'N')
and ar_ccuentr  is null


/*update RSFACCAR..AL0008ARTI
 set ar_ccuentr = ''
 where ar_ccuentr  is null
*/