USE [multi]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--  REVISAR QUE EL VIEW ESTE CON INNER JOIN !!!!!!!!!!!!!!!
--  SOLO PARA PRUEBAS INICIALES LO DEJE EN FULL OUTER JOIN
CREATE TABLE [dbo].PO_MOVI(
	[ID] [varchar](100) NOT NULL PRIMARY KEY,
	[PO] [char](2) NOT NULL,
	[UBI] [varchar](100) NULL,
	[EMPRESA] CHAR(4)	NOT NULL,	
	[MOV] CHAR(2) NOT NULL,
	[GUIA]  CHAR(11),
	[RUC]	CHAR(18),
	[DEFECTO] CHAR(2)	REFERENCES DEFECTOS(CODIGO) DEFAULT '',
	[PIEZA] CHAR(2)		REFERENCES PIEZAS(CODIGO) DEFAULT '',
	[SERVICIO] CHAR(2)	REFERENCES SERVICIOS(CODIGO) DEFAULT '',
	[CONDICION] CHAR(2) REFERENCES CONDICIONES (CODIGO) DEFAULT '',
	[CAN0] INT NOT NULL DEFAULT 0,
	[CAN1] INT NOT NULL DEFAULT 0,
	[CAN2] INT NOT NULL DEFAULT 0,
	[CAN3] INT NOT NULL DEFAULT 0,
	[CAN4] INT NOT NULL DEFAULT 0,
	[CAN5] INT NOT NULL DEFAULT 0,
	[CAN6] INT NOT NULL DEFAULT 0,
	[CAN7] INT NOT NULL DEFAULT 0,
	[CAN8] INT NOT NULL DEFAULT 0,
	[CAN9] INT NOT NULL DEFAULT 0,
	[USUARIO] CHAR(10) NULL,
	[FECHA] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[FECDOC] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
	[ESTADO] [char](1) NOT NULL DEFAULT 'A'

) ON [PRIMARY]


-- EMPRESAS
-- SELECT * FROM  RSCONCAR.dbo.CPCIAE


-- PROVEEDORES
-- SELECT * FROM  RSCONCAR..CP0001MAES WHERE AC_CVANEXO = 'P' AND LEN(AC_CCODIGO) = 11 

-- SELECT * FROM MODELADOR..[PO-DETA]