
CREATE TABLE GENEROS (
GENERO 		CHAR(2)		NOT NULL PRIMARY KEY,
DESCRIPCION	CHAR(100) 	NOT NULL,
USUARIO 	CHAR(10) 	NOT NULL,
FECHA		SMALLDATETIME	NOT NULL DEFAULT {FN NOW()},
ESTADO 		CHAR(1) 	NOT NULL DEFAULT 'A'
)
GO
CREATE TABLE [MERMAS] (
	[SERVICIOS] [float] NULL ,
	[TELAS] [float] NULL ,
	[AVIOS] [float] NULL ,
	[HILO] [float] NULL ,
	[TEJIDO] [float] NULL ,
	[TENIDO] [float] NULL ,
	[USUARIO] [char] (10)  NULL ,
	[FECHA] [smalldatetime] NULL ,
	[ESTADO] [char] (1) NULL DEFAULT 'A',
	[CORTE] [float] NULL ,
	[ACABADO] [float] NULL ,
	[COSTURA] [float] NULL ,
	[EMBALAJE] [float] NULL ,
	[ENCONADO] [char] (10)  NULL 
) ON [PRIMARY]
GO

SELECT * FROM PROPORCIONES