USE MODELADOR
GO


ALTER VIEW VIEW_POS

AS
SELECT        PP.PO, PP.COTIZACION AS COTI, PP.CLIENTE AS CLI, CL.NOMBRE AS NOM, PP.FECEMB AS EMB, PP.TIPOEMB AS TIP, PP.CANTIDAD AS CAN, ES.FOTO AS FOT, 
                         ES.CONTENIDO AS CON, PP.ESTADO AS EDO, PR.ESTILO AS CODEST, dbo.DESTINOS.NOMBRE, PP.DESTINO, TE.DESCRIPCION, PP.OFI, ES.ESTCLI, 
                         ES.CODARTICULO, ES.DESMODELADOR, PR.TEMPORADA, dbo.TEMPORADAS.DESCRIPCION AS DESTEM, ES.CODEST AS ESTILO
FROM            dbo.POS AS PP INNER JOIN
                         dbo.COTIZACION AS CC ON PP.COTIZACION = CC.COTIZACION INNER JOIN
                         dbo.PROTOS AS PR ON CC.PROTO = PR.PROTO AND CC.VERSION = PR.VERSION INNER JOIN
                         dbo.CLIENTE AS CL ON PP.CLIENTE = CL.CODIGO INNER JOIN
                         dbo.TIPOEMBARQUE AS TE ON PP.TIPOEMB = TE.CODIGO INNER JOIN
                         dbo.ESTILOS AS ES ON PR.CLIENTE = ES.CLIENTE AND PR.ESTILO = ES.CODEST INNER JOIN
                         dbo.DESTINOS ON PP.DESTINO = dbo.DESTINOS.CODIGO INNER JOIN
                         dbo.TEMPORADAS ON PR.CLIENTE = dbo.TEMPORADAS.CLIENTE AND PR.TEMPORADA = dbo.TEMPORADAS.CODIGO